// ── Single source of truth for all Clinical AI Analyzers ──────────────────────
// Import this wherever you need to show the analyzer list.
// All hubs, FAB, and AI Center page MUST use this registry — no duplicate lists.

import {
  Microscope, Layers, BookOpen, Brain, TestTube,
  Activity, Dna, HeartPulse, FlaskConical, Waves
} from "lucide-react";

// status: "active" = shown as fully functional; "beta" = shown with Educational/Beta badge
export const CLINICAL_AI_ANALYZERS = [
  {
    id: "urine",
    name: "Urine Pattern Analyzer",
    icon: TestTube,
    color: "bg-teal-600",
    page: "ClinicalAIHub",
    tab: "uds",
    status: "active",
    desc: "Urine dipstick, microscopy & pattern recognition — nephrotic, nephritic, UTI, tubular",
  },
  {
    id: "uds_interpreter",
    name: "UDS AI Interpreter",
    icon: Waves,
    color: "bg-violet-700",
    page: "ClinicalAIHub",
    tab: "uds_interpreter",
    status: "active",
    desc: "ICCS-based urodynamics · Bladder hostility grading · Renal risk · Full management outputs",
  },
  {
    id: "lab",
    name: "Lab Report Analyzer",
    icon: Microscope,
    color: "bg-rose-600",
    page: "ClinicalAIHub",
    tab: "labs",
    status: "active",
    desc: "Interpret blood work, RFT, CBC, electrolytes with pediatric reference ranges",
  },
  {
    id: "biopsy",
    name: "Renal Biopsy AI",
    icon: Microscope,
    color: "bg-violet-700",
    page: "ClinicalAIHub",
    tab: "biopsy",
    status: "active",
    desc: "Biopsy pattern interpretation: LM, IF, EM findings",
  },
  {
    id: "case",
    name: "Case Discussion AI",
    icon: BookOpen,
    color: "bg-emerald-700",
    page: "ClinicalAIHub",
    tab: "case",
    status: "active",
    desc: "Structured case analysis and management recommendations",
  },
  {
    id: "genetics",
    name: "Genetics AI",
    icon: Dna,
    color: "bg-violet-600",
    page: "ClinicalAIHub",
    tab: "genetics",
    status: "active",
    desc: "Genetic report interpretation, variant classification, counselling",
  },
  {
    id: "uroflow",
    name: "Uroflowmetry AI",
    icon: Activity,
    color: "bg-cyan-600",
    page: "ClinicalAIHub",
    tab: "uroflow",
    status: "active",
    desc: "Uroflow tracing pattern analysis — Qmax, Liverpool nomogram, dysfunctional voiding",
  },
  {
    id: "ecg",
    name: "ECG Analyzer",
    icon: HeartPulse,
    color: "bg-red-400",
    page: "ClinicalAIHub",
    tab: "ecg",
    status: "beta",
    betaLabel: "Educational only",
    desc: "Educational ECG pattern guide — not for primary diagnosis. Validate all findings clinically.",
  },
  {
    id: "radiology",
    name: "Radiology (Educational)",
    icon: Layers,
    color: "bg-sky-500",
    page: "ClinicalAIHub",
    tab: "radiology",
    status: "beta",
    betaLabel: "Educational only",
    desc: "Educational radiology guide — image AI is not validated for primary pathology identification. Use only for learning.",
  },
  {
    id: "differential",
    name: "Differential Dx",
    icon: Brain,
    color: "bg-indigo-600",
    page: "DifferentialEngine",
    tab: null,
    status: "active",
    desc: "Symptom-based AI differential with probability ranking",
  },
];