// ── Autoinflammatory Disease Expansion ───────────────────────────────────
// CAPS, TRAPS, MKD, DADA2, SAVI, Blau syndrome + Fever Pattern Engine

export const AUTOINFLAMMATORY_CONDITIONS = [
  {
    id: "caps",
    name: "CAPS (Cryopyrin-Associated Periodic Syndrome)",
    category: "Autoinflammatory",
    urgency: "critical",
    icd: "M04.2",
    guideline: "EUROFEVER/PRINTO CAPS Criteria + EMA Approval Canakinumab",
    tags: ["NLRP3", "Canakinumab", "IL-1", "Urticaria", "NOMID", "MWS", "FCAS"],
    variants: ["FCAS (Familial Cold Autoinflammatory Syndrome — mildest)", "MWS (Muckle-Wells — hearing loss)", "NOMID/CINCA (neonatal onset — most severe)"],
    overview: "IL-1β driven periodic fever syndrome. NLRP3 gain-of-function mutations. Spectrum from cold-triggered urticaria (FCAS) to chronic progressive neonatal multisystem inflammatory disease (NOMID) with joint deformity, CNS inflammation, deafness.",
    diagnostic_criteria: [
      "NLRP3 (CIAS1) gene mutation — diagnostic",
      "Urticarial rash (non-pruritic, neutrophilic infiltrate)",
      "Fever with elevated inflammatory markers (CRP, SAA)",
      "FCAS: cold-triggered episodes <24h",
      "MWS: sensorineural hearing loss, AA amyloidosis risk",
      "NOMID: continuous neonatal-onset, CNS inflammation, bony overgrowth, intellectual disability",
    ],
    flowchart: [
      "Recurrent urticarial rash + fever + elevated CRP/SAA — suspect CAPS",
      "NLRP3 gene sequencing — mutation diagnostic but 30% somatic mosaicism (standard sequencing may miss)",
      "Audiometry (MWS/NOMID), ophthalmology (papilloedema NOMID), CNS MRI (meningitis NOMID)",
      "Canakinumab 2–4 mg/kg SC q8 weeks (FDA/EMA approved) — all CAPS subtypes",
      "Alternative: anakinra 1–2 mg/kg/day SC (daily — good for dose titration)",
      "NOMID: canakinumab or rilonacept — urgent, progressive CNS/joint damage",
      "Monitor SAA levels — target <10 mg/L to prevent AA amyloidosis",
    ],
    decision_nodes: [
      { q: "NOMID/CINCA (neonatal, chronic, CNS/bone disease)?", yes: "Urgent canakinumab — permanent disability if untreated; ophthalmology + neurology", no: "FCAS/MWS: canakinumab 2 mg/kg q8w. Anakinra if rapid dose adjustment needed." },
      { q: "Elevated SAA despite treatment?", yes: "Escalate canakinumab dose or frequency; add IL-1 dose review", no: "Continue current dose; annual SAA surveillance for amyloid prevention" },
    ],
    key_points: [
      "Canakinumab: approved specific therapy — transforms quality of life",
      "SAA target <10 mg/L — prevents AA amyloidosis (major long-term risk)",
      "NOMID: neonatal chronic meningitis — permanent hearing/vision loss if delayed",
      "Somatic mosaicism: negative genetic test does not exclude CAPS — clinical diagnosis still valid",
      "All subtypes: IL-1 inhibition dramatically effective — consider therapeutic trial if diagnosis uncertain",
      "Avoid live vaccines on IL-1i therapy",
    ],
    monitoring: ["SAA monthly during titration, then q3 months", "CBC + CRP", "Audiometry (MWS/NOMID annually)", "Ophthalmology (NOMID)", "MRI brain (NOMID)", "Urine PCR (amyloid surveillance)"],
    drugs: ["Canakinumab (first-line)", "Anakinra (alternative/bridge)", "Rilonacept"],
    emergency_flags: ["NOMID: papilloedema (vision loss)", "Sensorineural deafness progression", "Amyloidosis-related nephrotic syndrome"],
    renal_overlap: ["AA amyloidosis → nephrotic syndrome", "Monitor urine protein annually", "ACEi if proteinuria develops"],
    prognosis: "FCAS: excellent with canakinumab. NOMID: improved with IL-1i but permanent disability if delayed. All: amyloidosis prevented with SAA suppression.",
    refs: [
      { title: "EUROFEVER CAPS Guidelines", url: "https://www.printo.it/" },
    ],
    evidence_grade: "Strong",
    last_updated: "2024-05",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "traps",
    name: "TRAPS (TNF Receptor-Associated Periodic Syndrome)",
    category: "Autoinflammatory",
    urgency: "medium",
    icd: "M04.1",
    guideline: "EUROFEVER/PRINTO TRAPS Criteria 2019",
    tags: ["TNFRSF1A", "Prolonged Fever", "Orbital Oedema", "Canakinumab", "Etanercept"],
    variants: ["High penetrance TNFRSF1A mutations (structural — severe)", "Low penetrance (R92Q, P46L variants — milder)"],
    overview: "Autosomal dominant periodic fever. TNFRSF1A mutations. Prolonged febrile attacks (7–21 days). Characteristic periorbital oedema, migratory rash, myalgia. Amyloidosis risk in high-penetrance mutations.",
    diagnostic_criteria: [
      "TNFRSF1A mutation (high or low penetrance)",
      "Febrile episodes >5 days (typically 7–21 days, longer than FMF)",
      "Migratory rash (centrifugal spread)",
      "Periorbital oedema",
      "Myalgia (migratory muscle pain)",
      "Abdominal pain, pleuritis",
      "Family history autosomal dominant",
    ],
    flowchart: [
      "Prolonged fever attacks >7d + periorbital oedema + migratory rash/myalgia",
      "TNFRSF1A gene sequencing",
      "Labs during attack: elevated CRP/ESR, SAA, leukocytosis",
      "Mild attacks: prednisolone 0.5–1 mg/kg/day for duration (effective but increases frequency)",
      "Moderate-severe or frequent: canakinumab 150 mg SC q8w (adults) / 2 mg/kg q8w (children)",
      "Etanercept 0.4 mg/kg SC biweekly: second-line (less effective than IL-1i)",
      "High-penetrance mutations: colchicine may reduce frequency",
      "Annual SAA monitoring — amyloidosis risk (high-penetrance mutations)",
    ],
    decision_nodes: [
      { q: "High-penetrance structural mutation (e.g. C30S, C33Y, T50M)?", yes: "Canakinumab first-line — high amyloidosis risk, suppress SAA aggressively", no: "Low-penetrance (R92Q): NSAIDs or short steroid course for attacks; IL-1i if frequent" },
    ],
    key_points: [
      "Attacks longer than FMF (>7 days) — key distinguisher",
      "Periorbital oedema is characteristic",
      "Steroids: effective for attack BUT increase attack frequency",
      "Canakinumab: now first-line for moderate-severe TRAPS",
      "Etanercept: second-line (less effective than in RA/JIA)",
      "IL-6i (tocilizumab): emerging evidence for TRAPS",
    ],
    monitoring: ["SAA q3 months", "Attack diary", "Urine PCR annually (amyloid)", "CBC, CRP"],
    drugs: ["Prednisolone (acute attacks)", "Canakinumab", "Etanercept", "Colchicine (adjunct)"],
    emergency_flags: ["Proteinuria developing (amyloid)", "Severe pleuritis mimicking pneumothorax", "Meningitis overlap"],
    renal_overlap: ["AA amyloidosis — same pathway as FMF amyloid", "SAA suppression prevents renal amyloid"],
    prognosis: "High-penetrance: amyloidosis if untreated. Canakinumab dramatically improves quality of life.",
    refs: [{ title: "EUROFEVER TRAPS 2019", url: "https://www.printo.it/" }],
    evidence_grade: "Moderate",
    last_updated: "2024-03",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "mkd",
    name: "MKD / HIDS (Mevalonate Kinase Deficiency)",
    category: "Autoinflammatory",
    urgency: "medium",
    icd: "E72.59",
    guideline: "EUROFEVER/PRINTO MKD Criteria 2019",
    tags: ["MVK", "Canakinumab", "Lymphadenopathy", "Periodic Fever", "Cervical Nodes"],
    overview: "Autosomal recessive. MVK gene mutations. Fever every 4–6 weeks (extremely regular). Cervical lymphadenopathy, aphthous ulcers, GI symptoms. MVA (severe) vs HIDS (mild) spectrum.",
    diagnostic_criteria: [
      "MVK gene mutation",
      "Regular febrile episodes every 4–6 weeks",
      "Cervical lymphadenopathy (characteristic)",
      "Aphthous stomatitis",
      "Abdominal pain, diarrhoea, vomiting",
      "Low mevalonate kinase enzyme activity (<1% normal)",
      "Elevated urinary mevalonic acid during attacks",
    ],
    flowchart: [
      "Regular fever every 4–6 weeks + cervical lymphadenopathy: suspect MKD",
      "MVK gene sequencing + enzyme activity measurement",
      "Urinary mevalonic acid during attack (elevated in both MVA and HIDS)",
      "IgD level >100 IU/mL (raised in 80% but not specific)",
      "Mild attacks: NSAIDs/prednisolone 1 mg/kg/day for duration",
      "Frequent/severe: canakinumab 150 mg q8w (children: 2 mg/kg q8w)",
      "Anakinra: alternative, faster onset",
    ],
    decision_nodes: [
      { q: "MVA (severe end — neurological, retinitis, ataxia)?", yes: "Aggressive IL-1 inhibition + haematology (HSCT in severe MVA)", no: "HIDS: canakinumab q8w, good quality of life response" },
    ],
    key_points: [
      "Most regular periodic fever — attacks every 4–6 weeks like clockwork",
      "Cervical lymphadenopathy is characteristic (vs FMF)",
      "IgD >100: suggestive but not specific",
      "Canakinumab: dramatic response in HIDS",
      "MVA (severe): simvastatin helps reduce MVA accumulation; HSCT in severe cases",
    ],
    monitoring: ["Attack diary (frequency)", "SAA q3 months", "CBC, CRP", "Urine PCR"],
    drugs: ["NSAIDs", "Prednisolone (acute)", "Canakinumab", "Anakinra", "Simvastatin (MVA)"],
    emergency_flags: ["MVA: cerebellar ataxia, retinitis (early visual changes)", "Severe abdominal pain (mimicking surgical abdomen)"],
    renal_overlap: ["Amyloidosis less common than FMF/TRAPS but possible — annual urine surveillance"],
    prognosis: "HIDS: good response to canakinumab. MVA: variable, can be severe.",
    refs: [{ title: "EUROFEVER MKD 2019", url: "https://www.printo.it/" }],
    evidence_grade: "Moderate",
    last_updated: "2024-02",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "dada2",
    name: "DADA2 (ADA2 Deficiency)",
    category: "Autoinflammatory",
    urgency: "critical",
    icd: "D89.3",
    guideline: "DADA2 International Collaboration + Navon Elkan 2014",
    tags: ["ADA2", "CECR1", "Stroke", "PAN-like", "TNFi", "HSCT"],
    overview: "Loss-of-function mutations in CECR1/ADA2 gene. Mimics PAN clinically. Presents with stroke (lacunar), livedo reticularis, systemic vasculitis, immunodeficiency, and/or cytopenias. TNFi is transformative treatment.",
    diagnostic_criteria: [
      "Low ADA2 enzyme activity (<20% normal)",
      "Biallelic CECR1 mutations",
      "Early-onset stroke (lacunar)",
      "Livedo reticularis / racemosa",
      "PAN-like vasculitis features",
      "Haematological: aplastic anaemia, pure red cell aplasia, lymphoproliferation",
    ],
    flowchart: [
      "Young child + stroke (lacunar on MRI) + livedo reticularis: suspect DADA2",
      "ADA2 enzyme activity in plasma (low sensitivity with commercial kits) + CECR1 gene sequencing",
      "CBC: cytopenias, hypogammaglobulinaemia",
      "MRI brain: multiple lacunar infarcts (bilateral, deep)",
      "Start TNFi URGENTLY: adalimumab 20–40 mg SC q2w (weight-based)",
      "Aspirin 3–5 mg/kg/day as anti-stroke",
      "AVOID corticosteroids as monotherapy (insufficient in DADA2)",
      "Severe haematological disease: HSCT — curative option",
    ],
    decision_nodes: [
      { q: "Active stroke or recurrent strokes on treatment?", yes: "Ensure adequate TNFi dosing; consider HSCT referral", no: "Continue adalimumab + aspirin; aspirin lifelong" },
      { q: "Severe cytopenias (aplastic anaemia / PRCA)?", yes: "HSCT referral — only cure for haematological DADA2", no: "Manage medically with TNFi + IVIG if hypogammaglobulinaemic" },
    ],
    key_points: [
      "DADA2 mimics PAN but is a distinct genetic disease — always test in child with PAN features",
      "TNFi (adalimumab) prevents strokes — can stop further vascular events",
      "HSCT: curative for haematological manifestations",
      "Corticosteroids alone: insufficient — do not use as monotherapy",
      "Aspirin: essential co-therapy for stroke prevention",
      "Screen siblings/family: autosomal recessive",
    ],
    monitoring: ["MRI brain q6–12 months (stroke surveillance)", "ADA2 enzyme (treatment monitoring)", "CBC (cytopenias)", "Immunoglobulins", "BP"],
    drugs: ["Adalimumab (TNFi — first-line)", "Etanercept (alternative TNFi)", "Aspirin", "IVIG (hypogammaglobulinaemia)"],
    emergency_flags: ["Acute stroke", "Haemorrhagic vasculitis", "Aplastic anaemia crisis"],
    renal_overlap: ["Renovascular involvement possible", "Monitor BP and GFR", "Renal aneurysms as in PAN"],
    prognosis: "Excellent with TNFi. HSCT resolves haematological disease. Without treatment: progressive strokes and disability.",
    refs: [
      { title: "Navon Elkan NEJM 2014 — DADA2 Discovery", url: "https://pubmed.ncbi.nlm.nih.gov/24482247/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-06",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "savi",
    name: "SAVI (STING-Associated Vasculopathy with Onset in Infancy)",
    category: "Autoinflammatory",
    urgency: "critical",
    icd: "M35.8",
    guideline: "SAVI International Collaborative + Liu 2014",
    tags: ["TMEM173", "Type I IFN", "ILD", "JAK Inhibitor", "Ulcers"],
    overview: "Rare type I interferonopathy. TMEM173/STING gain-of-function mutations. Neonatal/early childhood onset. Pulmonary fibrosis, systemic vasculopathy, skin ulcers, acral ischaemia. JAK inhibitors emerging treatment.",
    diagnostic_criteria: [
      "TMEM173 gain-of-function mutation",
      "Neonatal/early onset systemic inflammation",
      "Progressive ILD / pulmonary fibrosis",
      "Skin lesions: telangiectasia, livedo, ulcers, acral ischaemia",
      "Elevated type I IFN signature",
    ],
    flowchart: [
      "Infant/toddler: ILD + skin vasculopathy + systemic inflammation",
      "TMEM173 gene sequencing + type I IFN signature",
      "HRCT chest: ILD pattern (ground glass, fibrosis)",
      "No effective standard therapy — baricitinib (JAK1/2 inhibitor) showing promise",
      "Ruxolitinib: emerging evidence in refractory SAVI",
      "Supportive: oxygen, PFTs, physiotherapy",
      "Avoid steroids alone — minimal benefit",
    ],
    decision_nodes: [
      { q: "Rapidly progressive ILD?", yes: "Urgent JAK inhibitor trial (baricitinib) + pulmonology referral + HSCT consideration", no: "Baricitinib + close respiratory monitoring (PFTs q3–6 months)" },
    ],
    key_points: [
      "JAK inhibitors (baricitinib, ruxolitinib): current best evidence in SAVI",
      "Type I IFN signature: elevated IFN-stimulated gene score — diagnostic biomarker",
      "Progressive ILD: main cause of mortality",
      "HSCT: under investigation — may halt inflammation but not reverse fibrosis",
      "Specialist centre referral mandatory",
    ],
    monitoring: ["PFTs q3–6 months", "HRCT chest annually", "IFN signature", "CBC, CRP", "Echocardiogram (pulmonary HTN)"],
    drugs: ["Baricitinib", "Ruxolitinib", "Supportive (O2, pulmonary rehab)"],
    emergency_flags: ["Respiratory failure (acute ILD exacerbation)", "Severe acral ischaemia/gangrene"],
    renal_overlap: ["Minimal direct renal involvement — monitor for secondary effects"],
    prognosis: "Poor without treatment. JAK inhibitors may stabilise. Specialist centre essential.",
    refs: [{ title: "Liu NEJM 2014 — SAVI Discovery", url: "https://pubmed.ncbi.nlm.nih.gov/24499812/" }],
    evidence_grade: "Low (rare disease — case series only)",
    last_updated: "2024-04",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "blau",
    name: "Blau Syndrome / Early-Onset Sarcoidosis",
    category: "Autoinflammatory",
    urgency: "medium",
    icd: "M04.8",
    guideline: "EUROFEVER Blau/EOS Classification",
    tags: ["NOD2", "Uveitis", "Camptodactyly", "Granulomatous", "TNFi"],
    overview: "NOD2 gain-of-function mutations. Triad: granulomatous arthritis (camptodactyly), uveitis, skin rash (like salmon-colored). Autosomal dominant. Resembles sarcoidosis in young child.",
    diagnostic_criteria: [
      "NOD2 (CARD15) gain-of-function mutation",
      "Granulomatous arthritis with camptodactyly (boggy hand/foot joints)",
      "Anterior uveitis (may be severe)",
      "Granulomatous skin rash",
      "Family history autosomal dominant",
    ],
    flowchart: [
      "Camptodactyly + uveitis + skin rash in young child: suspect Blau",
      "NOD2 gene sequencing",
      "Ophthalmology: anterior (or panuveitis)",
      "Skin biopsy: non-caseating granulomata",
      "Corticosteroids + MTX for arthritis/uveitis",
      "TNFi (adalimumab/infliximab) for refractory disease",
      "Ophthalmology close follow-up (vision loss risk)",
    ],
    decision_nodes: [
      { q: "Severe/refractory uveitis?", yes: "Adalimumab (TNFi) — superior for uveitis + arthritis", no: "MTX + topical steroids for mild-moderate" },
    ],
    key_points: [
      "Camptodactyly: boggy non-erosive 'toad skin' joints — hallmark of Blau",
      "Unlike sarcoidosis: younger onset, NOD2 mutation, autosomal dominant",
      "Adalimumab: preferred TNFi for Blau with uveitis",
      "Systemic sarcoidosis complications (lung, kidney) can occur in severe/sporadic EOS",
    ],
    monitoring: ["Ophthalmology q3–6 months", "Joint function", "Skin assessment", "CBC on MTX"],
    drugs: ["Prednisolone", "Methotrexate", "Adalimumab", "Infliximab"],
    emergency_flags: ["Acute vision loss (panuveitis)", "Systemic granulomatous involvement (lung/liver)"],
    renal_overlap: ["Renal granulomata (rare)", "Hypercalciuria/hypercalcaemia from granulomata → nephrolithiasis"],
    prognosis: "Chronic course. Vision loss main morbidity. Joint function generally preserved.",
    refs: [{ title: "EUROFEVER Blau Recommendations", url: "https://www.printo.it/" }],
    evidence_grade: "Low (rare disease)",
    last_updated: "2024-02",
    review_status: "EXPERT_REVIEWED",
  },
];

// ── Fever Pattern Engine ──────────────────────────────────────────────────
export const FEVER_PATTERN_ENGINE = {
  patterns: [
    {
      id: "pfapa",
      name: "PFAPA (Periodic Fever, Aphthous Stomatitis, Pharyngitis, Adenitis)",
      features: { interval: "3–8 weeks", duration: "3–6 days", aphthae: true, pharyngitis: true, adenitis: true, rash: false, arthritis: false },
      treatment: "Single prednisolone dose 1 mg/kg — aborts episode dramatically (diagnostic and therapeutic). Tonsillectomy in refractory cases.",
      dnaTesting: "Not required — clinical diagnosis. No gene mutation.",
    },
    {
      id: "fmf",
      name: "FMF (Familial Mediterranean Fever)",
      features: { interval: "Irregular (days–weeks)", duration: "12–72 hours", peritonitis: true, pleuritis: true, arthritis: true, rash: "erysipelas-like erythema", ethnicity: ["Mediterranean", "Middle East", "Indian", "North African"] },
      treatment: "Colchicine lifelong. IL-1i if resistant.",
      dnaTesting: "MEFV gene sequencing",
    },
    {
      id: "traps",
      name: "TRAPS",
      features: { interval: "Variable", duration: "7–21 days", periorbitalOedema: true, migratoryRash: true, migratoryMyalgia: true, dominantInheritance: true },
      treatment: "Canakinumab (preferred). Steroids for acute attacks (worsen frequency).",
      dnaTesting: "TNFRSF1A gene sequencing",
    },
    {
      id: "caps_fcas",
      name: "CAPS-FCAS",
      features: { interval: "Cold-triggered", duration: "<24 hours", urticaria: true, coldTriggered: true },
      treatment: "Canakinumab",
      dnaTesting: "NLRP3 gene sequencing",
    },
    {
      id: "mkd",
      name: "MKD / HIDS",
      features: { interval: "Every 4–6 weeks (regular)", duration: "4–7 days", cervicalAdenopathy: true, aphthae: true, abdomen: true },
      treatment: "Canakinumab",
      dnaTesting: "MVK gene + enzyme activity",
    },
  ],
  differentials: (inputs) => {
    const results = [];
    if (inputs.aphthae && inputs.pharyngitis && inputs.adenitis && inputs.interval < 10) {
      results.push({ diagnosis: "PFAPA", probability: "High", key: "Aphthae + pharyngitis + adenitis; prednisolone response diagnostic" });
    }
    if (inputs.duration <= 3 && (inputs.ethnicity?.includes("Mediterranean") || inputs.ethnicity?.includes("Middle East"))) {
      results.push({ diagnosis: "FMF", probability: "High", key: "Short attacks <72h + Mediterranean ethnicity → colchicine trial" });
    }
    if (inputs.duration >= 7 && inputs.periorbitalOedema) {
      results.push({ diagnosis: "TRAPS", probability: "High", key: "Prolonged attacks >7d + periorbital oedema → TNFRSF1A testing" });
    }
    if (inputs.coldTriggered && inputs.urticaria) {
      results.push({ diagnosis: "CAPS-FCAS", probability: "High", key: "Cold-triggered urticaria <24h → NLRP3 testing + canakinumab" });
    }
    if (inputs.regularInterval && inputs.cervicalAdenopathy) {
      results.push({ diagnosis: "MKD/HIDS", probability: "Moderate", key: "Regular 4–6 week intervals + cervical nodes → MVK testing" });
    }
    if (results.length === 0) {
      results.push({ diagnosis: "Undifferentiated Periodic Fever", probability: "Uncertain", key: "Consider: genetic panel (FMF/TRAPS/CAPS/MKD), infectious workup, malignancy screen" });
    }
    return results;
  },
};