// ── Procedures Layer ──────────────────────────────────────────────────────

export const RHEUM_PROCEDURES = [
  {
    id: "joint_aspiration",
    name: "Joint Aspiration (Arthrocentesis)",
    category: "Joint Procedure",
    indications: ["Diagnostic: unclear joint effusion, exclude septic arthritis", "Therapeutic: tense painful effusion (knee, ankle, wrist)", "Pre-injection decompression"],
    contraindications: ["Overlying skin infection/cellulitis", "Prosthetic joint (specialist only)", "Coagulopathy (relative — correct INR first)", "Bacteraemia"],
    preparation: ["Consent (parent + patient if appropriate)", "US guidance recommended especially in hip/shoulder", "Sterile field, gloves, drape", "Local anaesthetic: EMLA cream 60 min prior or lidocaine 1% intradermal", "Equipment: 18–21G needle, 5–20 mL syringe"],
    technique: ["Position: knee — supine, slightly flexed; ankle — dorsiflexed neutral", "Landmark: knee — medial/lateral parapatellar, ankle — anteromedial", "Ultrasound guidance for small joints or obese patients", "Aspirate to dryness where possible", "Send: Gram stain + culture, cell count, crystals, protein, glucose"],
    interpretation: ["Normal: <200 WBC/mm³", "Inflammatory: 2000–50,000 WBC (PMN predominant)", "Septic: >50,000 WBC (>75% PMN) — treat as infected until proven otherwise", "Haemarthrosis: bloody — consider haemophilia, trauma, PVNS"],
    monitoring: ["Pain at site for 24–48h expected", "Watch for: increased pain, swelling, fever (septic joint post-procedure)", "Ice pack + rest 24h post-procedure"],
    complications: ["Iatrogenic infection (<0.1%)", "Haemarthrosis", "Injury to adjacent structures", "Vasovagal response"],
    consent: "Explain: benefits (diagnosis/relief), risks (infection <0.1%, haemarthrosis, temporary worsening), alternatives (conservative, imaging-guided).",
  },
  {
    id: "joint_injection",
    name: "Intraarticular Steroid Injection",
    category: "Joint Procedure",
    indications: ["JIA: active joint inflammation (≤2 joints)", "Refractory synovitis despite systemic therapy", "Tenosynovitis", "Bursitis"],
    contraindications: ["Local or systemic infection", "Unstable coagulopathy", ">3 injections same joint in 12 months", "Periarticular osteoporosis (relative)"],
    agents: ["Triamcinolone hexacetonide 20 mg/mL (PREFERRED for JIA — longer duration, superior efficacy)", "Triamcinolone acetonide 40 mg/mL (alternative)", "Methylprednisolone acetate (less preferred)", "Dose: 0.5–2 mL depending on joint size"],
    preparation: ["Fasting 2h if GA/sedation planned for young child", "EMLA cream 60 min before; Entonox for anxiety", "GA for hip, shoulder, or younger children (<3 years)", "Confirm no active infection — WBC, CRP"],
    technique: ["Aspirate before injecting if effusion present", "Confirm intraarticular position (US guidance preferred)", "Inject slowly — resistance suggests extraarticular placement", "Hip/shoulder: fluoroscopy or US mandatory"],
    monitoring: ["Post-injection flare common first 24–48h (normal — ice + rest)", "Activity restriction 24–48h post-injection", "Response assessment at 2–4 weeks", "Triamcinolone hexacetonide: duration 3–12 months"],
    complications: ["Skin atrophy/hypopigmentation (especially if extraarticular)", "Crystal arthritis (post-injection flare)", "Osteonecrosis (rare, with repeated injections)", "HPA axis suppression (rare, bilateral knee injections in small child)"],
    consent: "Benefits: local sustained anti-inflammatory effect. Risks: post-injection flare (normal), skin changes, infection, growth plate effects (avoid in children — use US guidance to avoid).",
  },
  {
    id: "ivig_infusion",
    name: "IVIG Infusion",
    category: "IV Therapy",
    indications: ["KD: 2 g/kg (standard)", "MIS-C: 2 g/kg", "JDM refractory", "IVIG replacement (hypogammaglobulinaemia)", "sJIA refractory", "ITP (bleeding risk)"],
    contraindications: ["IgA deficiency with anti-IgA antibodies (anaphylaxis risk — use IgA-depleted preparation)", "Severe cardiac failure (fluid overload risk)", "Active thrombosis (relative)"],
    preparation: ["Check IgA level before first infusion", "Pre-medications: paracetamol 15 mg/kg + diphenhydramine if prior reactions", "Baseline: BP, HR, temperature, weight", "IV access (large-bore preferred for 2 g/kg)"],
    infusion: ["Start at 0.5 mg/kg/min, increase q30 min if tolerated", "Max rate: 4 mg/kg/min", "KD 2 g/kg: infuse over 8–12 hours", "Total volume: can be significant (400 mL for 2 g/kg 20 kg patient)"],
    monitoring: ["BP, HR, temperature every 30 min", "Watch for: headache (aseptic meningitis rare), haemolysis, thromboembolic events", "Post-infusion: check response at 24–48h", "Repeat echo at 2 weeks (KD)"],
    complications: ["Headache (most common)", "Aseptic meningitis (rare — 1%)", "Haemolysis", "Acute kidney injury (sucrose-containing products)", "Transfusion-related reactions", "VTE"],
    consent: "Blood-derived product — inform parents about viral inactivation steps. Rare risk of transmitted infection. Benefits generally outweigh risks in all standard indications.",
  },
  {
    id: "plasma_exchange",
    name: "Therapeutic Plasma Exchange (PLEX/TPE)",
    category: "Extracorporeal",
    indications: ["ANCA vasculitis: creatinine >500 μmol/L or DAH", "cPACNS progressive", "Catastrophic APS", "TTP (ADAMTS13 deficiency)", "Severe MAS refractory"],
    contraindications: ["Active bleeding (relative)", "Haemodynamically unstable (stabilise first)", "No vascular access available", "Hypocalcaemia (from citrate — replace)"],
    preparation: ["Central venous access (CVC — 11.5Fr double/triple lumen)", "Baseline: CBC, coagulation, calcium, albumin, creatinine, BP", "Replacement fluid: 5% albumin (most common) or FFP (for TTP/cAPS)", "Volume: 1–1.5 plasma volumes per session (typically 40–60 mL/kg)"],
    procedure: ["1–5 sessions on alternate days for vasculitis (typically 7 sessions)", "Anticoagulation: citrate (preferred) or heparin", "Monitor calcium hourly — citrate chelates calcium", "Replace fibrinogen + clotting factors if using albumin replacement (depleted after 3–4 sessions)"],
    monitoring: ["Calcium every session (citrate use)", "Coagulation before each session", "Access site inspection daily", "Response: creatinine trend, ANCA titres, clinical improvement"],
    complications: ["Hypocalcaemia (citrate — paraesthesia, tetany)", "Line sepsis", "Bleeding (coagulation factor depletion)", "Hypotension", "Allergic reaction to replacement fluid"],
    consent: "Invasive procedure — explain: central line risks, infection, hypocalcaemia. Discuss expected number of sessions and monitoring.",
  },
  {
    id: "capillaroscopy",
    name: "Nailfold Capillaroscopy",
    category: "Diagnostic Procedure",
    indications: ["Raynaud's phenomenon: differentiate primary vs secondary", "Scleroderma / juvenile scleroderma evaluation", "Mixed connective tissue disease (MCTD)", "JDM (microangiopathy)", "Undifferentiated CTD with vascular features"],
    contraindications: ["Recent trauma/injury to fingers", "Active finger infection"],
    preparation: ["Patient at room temperature (avoid cold hands)", "Apply immersion oil to nailfold", "Dermatoscope or dedicated capillaroscope (×200 magnification preferred)", "Examine all 10 nailfolds; document worst area"],
    patterns: ["Normal: regular capillary loops, uniform spacing, no haemorrhage", "Early scleroderma: few giant capillaries, rare haemorrhage, preserved density", "Active scleroderma: giant capillaries, haemorrhage, capillary loss", "Late scleroderma: severe avascular areas, ramified capillaries", "Dermatomyositis/JDM: enlarged loops, haemorrhage, capillary drop-out"],
    interpretation: ["Primary Raynaud's: normal capillaroscopy pattern", "Scleroderma spectrum: abnormal pattern — early/active/late", "JDM: DM-pattern capillaroscopy is diagnostic support"],
    monitoring: ["Repeat q6–12 months to monitor progression in scleroderma/JDM"],
    complications: ["None — non-invasive procedure"],
    consent: "Non-invasive, painless — no formal consent required. Patient education about findings.",
  },
];