// ── Pediatric Rheumatology Clinical Data Library ──────────────────────────
// Evidence-based: ACR/EULAR/PRINTO/ILAR/BSR guidelines

export const RHEUM_DISEASES = [
  {
    id: "jia_oligoarticular",
    name: "JIA — Oligoarticular",
    category: "JIA",
    icd: "M08.4",
    summary: "Most common JIA subtype. ≤4 joints in first 6 months. Peak age 2–4y, predominantly female. High risk of asymptomatic uveitis.",
    acr_class: "ILAR 2004",
    key_features: [
      "≤4 joints affected in first 6 months",
      "ANA positive in 70–80% (uveitis risk)",
      "Knee most commonly affected",
      "Leg length discrepancy risk",
    ],
    uveitis_screening: {
      frequency: "Every 3 months (ANA+, <7y, <4y disease duration)",
      alternate: "Every 6 months (ANA−, older onset)",
      note: "Slit-lamp mandatory — asymptomatic in ~75%"
    },
    treatment_ladder: [
      "NSAIDs (naproxen 10–15 mg/kg/day)",
      "Intraarticular triamcinolone (triamcinolone hexacetonide preferred)",
      "Methotrexate (10–15 mg/m² weekly) — if inadequate NSAID response",
      "Abatacept or adalimumab — for persistent active disease",
    ],
    monitoring: ["CBC, LFT monthly on MTX", "Uveitis screening", "Growth assessment", "Joint assessment JADAS27"],
    emergency_flags: ["Sudden painful eye (anterior uveitis flare)", "Fever + joint swelling (consider MAS)"],
  },
  {
    id: "jia_polyarticular_rfneg",
    name: "JIA — Polyarticular RF−",
    category: "JIA",
    icd: "M08.3",
    summary: "≥5 joints in first 6 months, RF negative. Bimodal age distribution. More aggressive course than oligoarticular.",
    key_features: [
      "≥5 joints in first 6 months of disease",
      "RF negative, may be ANA+",
      "Symmetric small joint involvement",
      "Cervical spine and TMJ at risk",
    ],
    treatment_ladder: [
      "NSAIDs + early MTX (10–15 mg/m² PO/SC weekly)",
      "Folic acid 5 mg weekly (day after MTX)",
      "Add etanercept or adalimumab if MTX insufficient at 3–6 months",
      "Abatacept for TNFi failure",
      "Tocilizumab for systemic features",
    ],
    monitoring: ["CBC, LFT, creatinine q4–8 weeks on MTX", "DAS28/JADAS27 every visit", "DEXA if on steroids"],
    emergency_flags: ["C-spine subluxation risk — pre-procedure imaging", "MAS in systemic flare"],
  },
  {
    id: "jia_polyarticular_rfpos",
    name: "JIA — Polyarticular RF+",
    category: "JIA",
    icd: "M08.0",
    summary: "Adolescent-onset, RF positive, anti-CCP often positive. Closely resembles adult RA. Aggressive erosive disease.",
    key_features: [
      "≥5 joints, RF positive (×2, ≥3 months apart)",
      "Anti-CCP usually positive",
      "Symmetric small joints, erosive",
      "Peak onset age 10–16y",
    ],
    treatment_ladder: [
      "Early aggressive MTX + hydroxychloroquine",
      "Consider leflunomide if MTX intolerant",
      "Early biologics (TNFi) — adalimumab, etanercept",
      "Combination DMARD therapy",
      "JAK inhibitors (tofacitinib, baricitinib) for refractory",
    ],
    monitoring: ["RF, anti-CCP, ESR, CRP", "Joint X-ray for erosions annually", "JADAS, DAS28"],
    emergency_flags: ["Vasculitis manifestations", "Pulmonary involvement"],
  },
  {
    id: "jia_systemic",
    name: "JIA — Systemic (sJIA)",
    category: "JIA",
    icd: "M08.2",
    summary: "Quotidian fever ≥2 weeks + arthritis + one of: rash, lymphadenopathy, hepatosplenomegaly, serositis. Life-threatening MAS risk.",
    key_features: [
      "Quotidian (once-daily) fever ≥38.5°C",
      "Salmon-colored evanescent rash",
      "Arthritis (may lag fever)",
      "Elevated ferritin, S100 proteins",
      "HLH/MAS risk up to 10%",
    ],
    treatment_ladder: [
      "NSAIDs + systemic steroids for acute phase",
      "Anakinra (IL-1 blocker) — first-line biologic",
      "Canakinumab (IL-1β inhibitor) — monthly dosing",
      "Tocilizumab (IL-6 blocker) — alternate first-line",
      "Avoid MTX in active systemic phase",
    ],
    mas_alert: {
      triggers: ["Ferritin >500 ng/mL (rising rapidly)", "Falling ESR in active disease", "Pancytopenia", "Liver dysfunction", "DIC features"],
      action: "Immediate rheum/haem consultation. Consider bone marrow biopsy. IV anakinra or high-dose IV methylprednisolone.",
    },
    monitoring: ["Daily ferritin during flares", "CBC, LFT, fibrinogen, triglycerides", "Echocardiography for pericarditis"],
    emergency_flags: ["Ferritin >10,000 — MAS", "Pericardial effusion", "Pulmonary hypertension"],
  },
  {
    id: "jia_enthesitis",
    name: "JIA — Enthesitis-Related (ERA)",
    category: "JIA",
    icd: "M08.1",
    summary: "Arthritis + enthesitis OR arthritis/enthesitis with ≥2 of: SI joint tenderness, inflammatory back pain, HLA-B27+, family history SpA, acute anterior uveitis.",
    key_features: [
      "Predominantly males, age >8y",
      "HLA-B27 positive in ~80%",
      "Sacroiliitis, Achilles enthesitis",
      "Risk of ankylosing spondylitis",
      "Acute painful uveitis (unlike oligoarticular)",
    ],
    treatment_ladder: [
      "NSAIDs (indomethacin 2–3 mg/kg/day for back pain)",
      "Sulfasalazine for peripheral arthritis",
      "Anti-TNF (etanercept, adalimumab) — for axial disease or TNFi-eligible",
      "Secukinumab (IL-17A inhibitor) — for NSAID/TNFi failure",
    ],
    monitoring: ["MRI SI joints for axial disease", "HLA-B27", "BASDAI, BASFI scores", "Uveitis monitoring"],
    emergency_flags: ["Acute red eye with pain — anterior uveitis", "Severe back pain + fever (SI infection DDx)"],
  },
  {
    id: "jia_psoriatic",
    name: "JIA — Psoriatic",
    category: "JIA",
    icd: "M08.8",
    summary: "Arthritis + psoriasis OR arthritis + 2 of: dactylitis, nail pitting, family history of psoriasis.",
    key_features: [
      "Dactylitis ('sausage digit')",
      "Nail pitting/onycholysis",
      "Asymmetric oligoarthritis",
      "Bimodal onset: 2–4y and 9–11y",
    ],
    treatment_ladder: [
      "NSAIDs for mild joint disease",
      "MTX (benefits skin + joints)",
      "TNFi — etanercept, adalimumab",
      "IL-17 inhibitors for psoriasis-dominant",
      "IL-12/23 inhibitors (ustekinumab) in adolescents",
    ],
    monitoring: ["Skin + joint assessment", "Uveitis screening (ANA+)", "PASI score for skin"],
    emergency_flags: ["Pustular psoriasis flare", "Erythroderma"],
  },
  {
    id: "pediatric_sle",
    name: "Pediatric SLE",
    category: "SLE",
    icd: "M32.9",
    summary: "Multisystem autoimmune disease. More severe in children than adults. ACR/EULAR 2019 classification criteria.",
    key_features: [
      "ANA >1:80 (>97% sensitive)",
      "Anti-dsDNA, anti-Sm, antiphospholipid antibodies",
      "Malar rash, discoid rash, photosensitivity",
      "Renal (most common severe organ): nephritis in ~60–80%",
      "Neuropsychiatric SLE (NPSLE)",
      "Cytopenias, serositis",
    ],
    classification: {
      criteria: "ACR/EULAR 2019 weighted criteria",
      minimum_score: "≥10 points (with ANA ≥1:80 entry criterion)",
      domains: ["Constitutional", "Hematologic", "Neuropsychiatric", "Mucocutaneous", "Serosal", "Musculoskeletal", "Renal", "Immunologic"]
    },
    treatment: {
      mild: ["Hydroxychloroquine 5 mg/kg/day (ALL patients)", "NSAIDs for arthralgia", "Sunscreen strictly"],
      moderate: ["Low-dose prednisolone 0.5 mg/kg/day", "Add MTX or azathioprine"],
      severe: ["High-dose prednisolone 1–2 mg/kg/day", "IV methylprednisolone pulses", "MMF or cyclophosphamide for nephritis"],
      biologic: ["Belimumab (BLyS inhibitor) — for refractory/steroid-sparing", "Anifrolumab (type I IFN inhibitor) — adults, evidence emerging in children", "Rituximab for refractory cytopenias/nephritis"],
    },
    lupus_nephritis: {
      classes: [
        "Class I — Minimal mesangial",
        "Class II — Mesangial proliferative",
        "Class III — Focal proliferative (active <50% glomeruli)",
        "Class IV — Diffuse proliferative (active ≥50% glomeruli) — MOST SEVERE",
        "Class V — Membranous",
        "Class VI — Advanced sclerosing",
      ],
      treatment_III_IV: [
        "Induction: IV methylprednisolone 3 pulses → oral prednisolone 1 mg/kg/day",
        "MMF 2–3 g/day (preferred) OR cyclophosphamide (NIH or Euro-Lupus protocol)",
        "Hydroxychloroquine to continue",
        "Maintenance: MMF 1–2 g/day + low-dose steroid",
        "Belimumab add-on for flare prevention",
        "Voclosporin — calcineurin inhibitor for class V/III+V",
      ],
      monitoring: ["Urinalysis, PCR monthly", "C3/C4, dsDNA every 3 months", "GFR trend", "BP control <130/80 (or age-adjusted)"],
      nephrology_overlap: "Mandatory nephrology co-management for Class III/IV/V"
    },
    monitoring: ["SLEDAI-2K every visit", "Anti-dsDNA, C3/C4", "CBC, LFT, renal function", "Urine PCR", "Ophthalmology (HCQ)", "DEXA yearly"],
    emergency_flags: ["NPSLE — seizure, psychosis", "Catastrophic APS (thrombosis)", "Diffuse alveolar hemorrhage", "Severe thrombocytopenia <20k", "Lupus nephritis flare (rising creatinine + haematuria)"],
  },
  {
    id: "kawasaki",
    name: "Kawasaki Disease",
    category: "Vasculitis",
    icd: "M30.3",
    summary: "Acute medium vessel vasculitis predominantly in <5y. Risk of coronary artery aneurysm (CAA). IVIG + aspirin cornerstone treatment.",
    key_features: [
      "Fever ≥5 days + ≥4 of 5 principal features",
      "Bilateral non-purulent conjunctival injection",
      "Polymorphous rash",
      "Strawberry tongue, cracked lips, oral erythema",
      "Extremity changes (erythema, desquamation)",
      "Cervical lymphadenopathy ≥1.5cm",
    ],
    incomplete_kd: {
      criteria: "Fever ≥5 days + 2–3 features + echo/lab supporting",
      labs: ["CRP ≥3 mg/dL, ESR ≥40 mm/h", "Albumin ≤3 g/dL", "Anaemia for age", "ALT elevated", "Platelets ≥450k after day 7", "WBC ≥15k", "Urine WBC ≥10/hpf"],
      echo_criteria: "Z-score ≥2.5, or LCA/RCA dilation"
    },
    treatment: [
      "IVIG 2 g/kg over 8–12 hours (single dose, within 10 days of fever)",
      "Aspirin 80–100 mg/kg/day (anti-inflammatory) until afebrile 48–72h, then 3–5 mg/kg/day",
      "IVIG-resistant (fever persists/recurs 36h post-IVIG): second IVIG 2g/kg OR infliximab 5mg/kg",
      "Methylprednisolone for high-risk (Kobayashi score ≥5 or Japanese guidelines)",
      "Cyclosporin for refractory cases",
    ],
    coronary_risk: {
      z_score: [
        "Normal: Z < 2.0",
        "Dilation: Z 2.0–2.5",
        "Small aneurysm: Z 2.5–5.0",
        "Medium aneurysm: Z 5.0–10.0",
        "Giant aneurysm: Z ≥10.0 or absolute >8mm"
      ],
      echo_timing: ["Baseline at diagnosis", "6–8 weeks", "1 year (or sooner if abnormal)"],
    },
    monitoring: ["Echo at diagnosis, 2 weeks, 6 weeks", "CBC, ESR, CRP, LFT, echo", "Long-term cardiology follow-up if CAA"],
    emergency_flags: ["Myocarditis/myocardial dysfunction", "Coronary artery aneurysm rupture", "MAS (ferritin, cytopenias)"],
  },
  {
    id: "misc",
    name: "MIS-C (Multisystem Inflammatory Syndrome in Children)",
    category: "Vasculitis",
    icd: "M35.8",
    summary: "Post-COVID-19 hyperinflammatory syndrome. Fever + multisystem inflammation + SARS-CoV-2 evidence. Kawasaki-like but more severe cardiovascular involvement.",
    key_features: [
      "Age <21y, fever ≥24h",
      "Laboratory evidence of inflammation",
      "Multisystem involvement (≥2 organs)",
      "SARS-CoV-2 exposure or seropositivity",
      "KD-like features in 50–60%",
      "Myocardial dysfunction, shock in 50%",
    ],
    who_criteria: {
      required: ["Child/adolescent 0–19y", "Fever ≥3 days", "Two of: rash/conjunctivitis, hypotension/shock, GI features, cardiac dysfunction, coagulopathy, CNS features", "Elevated CRP/ESR/ferritin/procalcitonin/fibrinogen", "No alternative diagnosis"],
      sars_cov2: "Positive PCR, antigen, or serology OR COVID contact"
    },
    treatment: [
      "IVIG 2 g/kg (if KD-like or fever + elevated inflammatory markers)",
      "IV methylprednisolone 2 mg/kg/day (AHA preferred for cardiac dysfunction)",
      "Aspirin 3–5 mg/kg/day (KD-like) or anticoagulation if CAA",
      "Anakinra for refractory or MAS-like",
      "ICU if shock: inotropes, IV fluids, ECMO",
    ],
    monitoring: ["Echo at diagnosis, 2 weeks, 6 weeks", "Troponin, BNP, ferritin, d-dimer", "CBC, CRP, fibrinogen", "ECG"],
    emergency_flags: ["Cardiogenic shock", "Coronary aneurysm", "MAS", "AKI (nephrology involvement)"],
  },
  {
    id: "mas_hlh",
    name: "MAS / HLH",
    category: "Autoinflammatory",
    icd: "D76.1",
    summary: "Macrophage Activation Syndrome = reactive HLH. Most common in sJIA and SLE. Life-threatening cytokine storm. HScore and 2016 MAS-sJIA criteria.",
    key_features: [
      "Unremitting fever",
      "Rapidly rising ferritin (often >10,000 ng/mL)",
      "Cytopenias (falling WBC, Hb, platelets)",
      "Falling (!) ESR despite fever",
      "Hepatosplenomegaly",
      "Coagulopathy (DIC)",
      "CNS dysfunction",
    ],
    diagnostic_criteria_2016: {
      required: "Known/suspected sJIA",
      fever: "Yes",
      ferritin: ">684 ng/mL",
      plus_any_2: [
        "Platelets ≤181×10⁹/L",
        "AST >48 U/L",
        "Triglycerides >156 mg/dL",
        "Fibrinogen ≤360 mg/dL"
      ]
    },
    h_score_factors: ["Temp >38.9°C", "Organomegaly", "Cytopenias", "Ferritin >2000", "Triglycerides", "Fibrinogen", "SGOT", "Bone marrow haemophagocytosis", "Known immunosuppression"],
    treatment: [
      "IV methylprednisolone 30 mg/kg/day (max 1g) × 3 days",
      "Cyclosporin 3–5 mg/kg/day IV — key for sJIA-MAS",
      "IV anakinra (escalating doses 2–8 mg/kg) — sJIA-MAS",
      "HLH-94/HLH-2004 protocol for primary or refractory (etoposide-based)",
      "IVIG for viral-triggered",
      "Ruxolitinib for refractory",
    ],
    monitoring: ["Daily ferritin, CBC, fibrinogen, triglycerides, LFT", "Bone marrow biopsy if diagnosis uncertain", "Neurological status"],
    emergency_flags: ["Ferritin >10,000 — ICU", "DIC", "Pulmonary haemorrhage", "Multiorgan failure"],
  },
  {
    id: "juvenile_dermatomyositis",
    name: "Juvenile Dermatomyositis (JDM)",
    category: "Myositis",
    icd: "M33.0",
    summary: "Inflammatory myopathy with characteristic skin findings. Gottron papules and heliotrope rash are pathognomonic. Calcinosis a major complication.",
    key_features: [
      "Proximal muscle weakness (Gowers sign)",
      "Gottron papules (extensor joints)",
      "Heliotrope rash (periorbital violaceous)",
      "Elevated muscle enzymes (CK, LDH, aldolase)",
      "Calcinosis in 30–70% (especially if delayed treatment)",
      "Interstitial lung disease (anti-MDA5, anti-Jo-1)",
    ],
    myositis_antibodies: [
      "Anti-MDA5 — rapid ILD, amyopathic DM",
      "Anti-TIF1γ — older onset, photodistributed rash",
      "Anti-NXP2 — calcinosis, severe muscle disease",
      "Anti-Mi-2 — classic skin rash, good prognosis",
      "Anti-Jo-1 — ILD, mechanic's hands",
    ],
    treatment: [
      "High-dose prednisolone 2 mg/kg/day (max 60mg) + MTX 15 mg/m² weekly",
      "IV methylprednisolone pulses for severe disease",
      "IVIG 2g/kg monthly for refractory or calcinosis",
      "Cyclosporin for ILD/refractory",
      "Rituximab for refractory/severe",
      "Sunscreen, photoprotection (critical)",
    ],
    cmas_note: "Use CMAS (Childhood Myositis Assessment Scale) for disease activity",
    monitoring: ["CMAS score", "CK, LDH, aldolase", "Pulmonary function tests", "MRI muscle (STIR sequence)", "HRCT chest for ILD"],
    emergency_flags: ["Respiratory failure (ILD/respiratory muscle)", "Dysphagia (aspiration risk)", "Rapidly progressive calcinosis"],
  },
  {
    id: "fmf",
    name: "FMF (Familial Mediterranean Fever)",
    category: "Autoinflammatory",
    icd: "E85.0",
    summary: "Most common hereditary periodic fever. MEFV gene mutations. Autosomal recessive. Colchicine is curative-level treatment.",
    key_features: [
      "Recurrent febrile episodes 12–72 hours",
      "Peritonitis (abdominal pain most common)",
      "Pleuritis, pericarditis",
      "Acute arthritis (monoarthritis, large joints)",
      "Erysipelas-like erythema",
      "Risk of secondary amyloidosis (AA amyloid — renal)",
    ],
    mefv_mutations: ["M694V (most severe, amyloid risk)", "M680I", "V726A", "E148Q (less pathogenic)"],
    tel_hashomer_criteria: {
      major: ["Peritonitis", "Pleuritis/pericarditis", "Monoarthritis (hip/knee/ankle)", "Fever alone"],
      minor: ["Incomplete attacks in one major site", "Erysipelas-like erythema", "Positive FMF family history"],
      diagnosis: "2 major OR 1 major + 2 minor OR 1 major + 5 supportive"
    },
    treatment: [
      "Colchicine 0.5–2 mg/day (weight-based) — lifelong",
      "Target: attack-free or <1 attack/month",
      "Anakinra (IL-1Ra) for colchicine-resistant",
      "Canakinumab for refractory/frequent attacks",
      "Rilonacept — alternate IL-1 blocker",
    ],
    amyloid_surveillance: ["Urine protein annually", "Serum amyloid A level", "Kidney biopsy if proteinuria"],
    monitoring: ["Attack diary", "SAA level (target <10 mg/L)", "Renal function, urine PCR", "Growth on colchicine"],
    emergency_flags: ["Renal amyloidosis (nephrotic syndrome)", "Cardiac tamponade", "Bowel obstruction (adhesions)"],
  },
  {
    id: "pfapa",
    name: "PFAPA Syndrome",
    category: "Autoinflammatory",
    icd: "R50.9",
    summary: "Periodic Fever, Aphthous stomatitis, Pharyngitis, Adenitis. Most common periodic fever in Western children. Benign, self-limiting.",
    key_features: [
      "Regular febrile episodes every 3–8 weeks",
      "Aphthous stomatitis",
      "Pharyngitis (exudative in 40%)",
      "Cervical lymphadenopathy",
      "Onset <5y, equal sex distribution",
      "Normal between attacks",
    ],
    eurofever_criteria: {
      required: "Periodic fever + no URTI",
      plus_3_of: ["Aphthous stomatitis", "Cervical adenitis", "Pharyngitis"],
      supportive: "Complete resolution with single oral steroid dose"
    },
    treatment: [
      "Prednisolone 1–2 mg/kg single dose at fever onset → aborts episode in hours",
      "Cimetidine 20–40 mg/kg/day — reduces attack frequency",
      "Colchicine — reduces frequency in some",
      "Tonsillectomy — curative in 60–80% of refractory cases",
    ],
    monitoring: ["Attack frequency and duration diary", "Exclude cyclic neutropenia (CBC during and between attacks)", "Exclude FMF/TRAPS if atypical"],
    emergency_flags: ["Febrile seizure", "Severe dehydration during episode"],
  },
  {
    id: "caps",
    name: "CAPS (Cryopyrin-Associated Periodic Syndromes)",
    category: "Autoinflammatory",
    icd: "M04.2",
    summary: "Spectrum of NLRP3 mutations: FCAS → MWS → NOMID/CINCA. Progressive severity. IL-1 inhibitors are disease-modifying.",
    subtypes: [
      "FCAS (Familial Cold Autoinflammatory Syndrome) — cold-triggered, mild",
      "MWS (Muckle-Wells Syndrome) — urticarial rash, sensorineural deafness, amyloidosis",
      "NOMID/CINCA — severe, chronic CNS inflammation, arthropathy, optic neuropathy"
    ],
    key_features: [
      "Urticarial (non-pruritic) rash",
      "Arthralgia/arthritis",
      "Conjunctivitis",
      "Sensorineural hearing loss (MWS, NOMID)",
      "Chronic meningitis (NOMID)",
      "Amyloidosis risk",
    ],
    treatment: [
      "Anakinra (IL-1Ra) — 1–2 mg/kg/day SC",
      "Canakinumab (IL-1β) — 2 mg/kg SC q8 weeks (MWS/NOMID, approved)",
      "Rilonacept — for FCAS/MWS",
      "Lifelong IL-1 inhibition required",
    ],
    monitoring: ["SAA level (amyloid risk)", "Audiometry annually", "Ophthalmology (papilloedema in NOMID)", "MRI brain (NOMID)", "Inflammatory markers"],
    emergency_flags: ["Raised ICP (NOMID)", "Vision loss", "Renal amyloidosis"],
  },
  {
    id: "traps",
    name: "TRAPS (TNF Receptor-Associated Periodic Syndrome)",
    category: "Autoinflammatory",
    icd: "M04.1",
    summary: "TNFRSF1A gene mutations. Prolonged episodes (>7 days). Dominant inheritance. Amyloidosis risk.",
    key_features: [
      "Prolonged fever episodes 7–21 days",
      "Migratory myalgia/periorbital oedema",
      "Monocytic skin fasciitis",
      "Abdominal pain, serositis",
      "Autosomal dominant (family history)",
    ],
    treatment: [
      "NSAIDs for mild attacks",
      "Corticosteroids (reduce episode severity but not frequency)",
      "Etanercept (TNFi) — can worsen in some TNFRSF1A mutations",
      "Anakinra — preferred biologic for TRAPS",
      "Canakinumab — approved for TRAPS",
    ],
    monitoring: ["SAA level", "Amyloid surveillance", "Attack diary", "Genetic testing TNFRSF1A"],
    emergency_flags: ["Renal amyloidosis", "Bowel perforation (rare)", "Orbital myositis"],
  },
  {
    id: "pediatric_vasculitis",
    name: "Pediatric Vasculitis (IgAV/HSP, ANCA, PAN)",
    category: "Vasculitis",
    icd: "D69.0",
    summary: "IgA Vasculitis (Henoch-Schönlein Purpura) most common. ANCA vasculitis (GPA, MPA) rare but severe. PAN requires aggressive therapy.",
    diseases: [
      {
        name: "IgA Vasculitis (IgAV/HSP)",
        features: ["Palpable purpura (legs/buttocks)", "Arthritis/arthralgia", "Abdominal pain", "Renal (IgA nephropathy pattern)"],
        treatment: ["Supportive + NSAIDs", "Steroids for GI/renal involvement", "Azathioprine/MMF for nephritis", "Cyclophosphamide for severe nephritis"],
        nephrology_overlap: "IgAV nephritis: ACE inhibitor, steroids, consider ECOG protocol"
      },
      {
        name: "GPA (Granulomatosis with Polyangiitis)",
        features: ["Respiratory (sinusitis, pulmonary haemorrhage)", "Renal (RPGN, ANCA+)", "c-ANCA/PR3 positive"],
        treatment: ["Induction: rituximab 375mg/m² ×4 OR cyclophosphamide", "High-dose steroids", "Maintenance: azathioprine or rituximab"],
        nephrology_overlap: "RPGN — urgent kidney biopsy, plasmapheresis for crescentic nephritis"
      },
      {
        name: "MPA (Microscopic Polyangiitis)",
        features: ["Glomerulonephritis, pulmonary haemorrhage", "p-ANCA/MPO positive"],
        treatment: ["Same as GPA — rituximab or cyclophosphamide induction"],
        nephrology_overlap: "Rapidly progressive GN — dialysis may be required"
      },
      {
        name: "Polyarteritis Nodosa (PAN)",
        features: ["Medium vessel, systemic symptoms", "Mononeuritis multiplex", "Livedo reticularis", "Hypertension, renal infarcts"],
        treatment: ["Prednisolone + cyclophosphamide", "Rituximab for ANCA+ variants"],
        nephrology_overlap: "Renal artery involvement — renovascular hypertension, renal infarcts"
      },
    ],
    bvas_note: "Use BVAS (Birmingham Vasculitis Activity Score) for disease activity assessment",
    monitoring: ["ANCA titre", "BVAS score", "Urinalysis, PCR", "Renal function", "Chest imaging"],
    emergency_flags: ["Pulmonary haemorrhage", "RPGN", "Mesenteric ischaemia", "Hypertensive emergency"],
  },
  {
    id: "uveitis",
    name: "Uveitis in Paediatric Rheumatic Disease",
    category: "Uveitis",
    icd: "H20.9",
    summary: "Mostly associated with JIA (oligoarticular, psoriatic). Can be asymptomatic. Leading cause of preventable blindness in JIA.",
    types: [
      "Anterior uveitis (most common in JIA) — often asymptomatic",
      "Acute anterior uveitis — painful, in ERA/SpA",
      "Intermediate uveitis — pars planitis",
      "Posterior/panuveitis — SLE, Behçet, sarcoid",
    ],
    screening_jia: {
      high_risk: "ANA+, oligoarticular, <7y onset, <4y disease → slit-lamp q3 months",
      medium_risk: "ANA+, other subtypes → q6 months",
      low_risk: "ANA−, ERA, psoriatic → q12 months",
    },
    treatment: [
      "Topical steroids + cycloplegics (acute)",
      "Sub-Tenon triamcinolone",
      "MTX (10–15 mg/m² weekly) — systemic steroid-sparing",
      "Adalimumab — approved for JIA-uveitis (TNFi of choice)",
      "Abatacept for TNFi failure",
      "Tocilizumab for refractory",
    ],
    complications: ["Band keratopathy", "Posterior synechiae", "Cataract", "Glaucoma", "Vision loss"],
    monitoring: ["Slit-lamp exam frequency per risk", "Visual acuity", "IOP (glaucoma screen)"],
    emergency_flags: ["Acute painful red eye (anterior uveitis flare)", "Sudden visual loss"],
  },
];

export const RHEUM_CATEGORIES = ["All", "JIA", "SLE", "Vasculitis", "Myositis", "Autoinflammatory", "Uveitis"];

export const NEPHROLOGY_OVERLAPS = [
  {
    condition: "Lupus Nephritis",
    rheum_disease: "Pediatric SLE",
    risk: "Very High",
    key_points: [
      "Affects 60–80% of pediatric SLE patients",
      "Mandatory renal biopsy for classification (ISN/RPS)",
      "Class III/IV require aggressive immunosuppression",
      "Target urine PCR <0.5 on maintenance",
      "Monitor GFR trajectory — CKD risk",
    ],
    emergency_flags: ["Rapidly rising creatinine", "Heavy proteinuria >3g/day", "Haematuria + casts"],
  },
  {
    condition: "IgAV Nephritis",
    rheum_disease: "IgA Vasculitis (HSP)",
    risk: "Moderate-High",
    key_points: [
      "Occurs in 40–60% of IgAV",
      "Usually mild (haematuria + mild proteinuria)",
      "Severe (nephrotic + nephritic) requires steroids ± IST",
      "ACE inhibitor for persistent proteinuria",
      "Rare risk of ESRD in severe presentations",
    ],
    emergency_flags: ["Nephrotic syndrome", "AKI", "RPGN pattern"],
  },
  {
    condition: "ANCA Vasculitis — RPGN",
    rheum_disease: "GPA / MPA",
    risk: "Very High",
    key_points: [
      "Rapidly progressive crescentic GN",
      "Urgent renal biopsy",
      "Plasmapheresis for severe (creatinine >500 μmol/L or DAH)",
      "Cyclophosphamide or rituximab induction",
      "Dialysis may be required acutely",
    ],
    emergency_flags: ["Creatinine doubling in <1 week", "Pulmonary haemorrhage (DAH)", "Oliguria/anuria"],
  },
  {
    condition: "Calcineurin Inhibitor Nephrotoxicity",
    rheum_disease: "JIA / JDM / SLE",
    risk: "Moderate",
    key_points: [
      "Cyclosporin/tacrolimus used in JDM, SLE, JIA",
      "Monitor trough levels (cyclosporin target 100–150 ng/mL)",
      "GFR monitoring mandatory",
      "Avoid NSAIDs concurrently",
      "Hypertension management",
    ],
    emergency_flags: ["Rising creatinine >30% baseline", "Severe hypertension"],
  },
  {
    condition: "Renal Amyloidosis",
    rheum_disease: "FMF / TRAPS / MWS (CAPS)",
    risk: "Moderate (if uncontrolled)",
    key_points: [
      "AA amyloidosis from chronic inflammation",
      "Presents as nephrotic syndrome",
      "Renal biopsy — Congo red + amyloid typing",
      "Treat underlying disease aggressively",
      "ACE inhibitor for proteinuria",
    ],
    emergency_flags: ["Nephrotic syndrome in periodic fever patient", "Rapidly declining GFR"],
  },
  {
    condition: "AKI in MIS-C / MAS",
    rheum_disease: "MIS-C, sJIA-MAS",
    risk: "High",
    key_points: [
      "AKI in up to 30% of MIS-C (shock, cytokine storm)",
      "May require renal replacement therapy",
      "Monitor urine output, creatinine daily in acute phase",
      "Avoid nephrotoxic drugs (NSAIDs, contrast)",
    ],
    emergency_flags: ["Oliguria in MIS-C", "Creatinine >2× baseline", "Haematuria in shock"],
  },
];