// ── Pediatric Rheumatology Disease Conditions Library ──────────────────────
// Matches GN pathway architecture: flowchart, decisionNodes, keyPoints, refs

export const RHEUM_CONDITIONS = [
  // ── JIA GROUP ────────────────────────────────────────────────────────────
  {
    id: "jia_oligo",
    name: "JIA — Oligoarticular",
    category: "JIA",
    urgency: "medium",
    icd: "M08.4",
    guideline: "ACR 2022 JIA Recommendations + PRINTO 2023",
    tags: ["ANA+", "Uveitis Risk", "ILAR", "Methotrexate"],
    variants: ["Persistent oligoarticular (≤4 joints throughout)", "Extended oligoarticular (>4 joints after 6 months)"],
    overview: "Most common JIA subtype (50%). ≤4 joints in first 6 months. Peak age 2–4y, predominantly female. High risk asymptomatic anterior uveitis.",
    classification: "ILAR 2004: ≤4 joints affected in first 6 months of disease. ANA positive in 70–80%. Extended subtype if ≥5 joints after 6m.",
    diagnostic_criteria: [
      "Arthritis in ≤4 joints in first 6 months",
      "Onset age <16y, arthritis persisting ≥6 weeks",
      "Exclude: psoriatic, ERA, systemic, RF+ polyarticular, enthesitis",
      "ANA testing mandatory (uveitis risk stratification)",
      "ESR, CRP, CBC, ANA, RF — baseline labs",
    ],
    flowchart: [
      "Confirm JIA: arthritis ≥6 weeks, onset <16y, ≤4 joints — check ANA, RF, CBC, ESR",
      "Rule out: septic arthritis, reactive arthritis, Lyme, malignancy (CBC + LDH)",
      "Ophthalmology referral URGENT — slit-lamp uveitis screening (silent in 75%)",
      "Start NSAID: naproxen 10–15 mg/kg/day or ibuprofen 30–40 mg/kg/day",
      "Intraarticular triamcinolone (hexacetonide preferred) for 1–2 large joints",
      "If inadequate response at 3 months: start MTX 10–15 mg/m² weekly SC/PO + folic acid",
      "If MTX fails at 3–6 months: biologic — adalimumab (TNFi) first-line for uveitis too",
    ],
    decision_nodes: [
      { q: "ANA+ AND onset <7y AND disease <4y?", yes: "Uveitis q3 months slit-lamp (high risk)", no: "Uveitis q6–12 months (standard risk)" },
      { q: "Active uveitis requiring systemic therapy?", yes: "Adalimumab (TNFi) — superior to etanercept for uveitis", no: "Continue MTX if joint response adequate" },
    ],
    key_points: [
      "Slit-lamp uveitis screening mandatory — asymptomatic in ~75% (ANA+ high risk)",
      "NSAID + intraarticular steroid (triamcinolone hexacetonide) first-line",
      "MTX 10–15 mg/m² weekly SC — preferred route; add folic acid 5 mg/week",
      "Adalimumab preferred over etanercept when uveitis is present",
      "Abatacept for TNFi failure; tocilizumab as alternative",
      "Extended oligoarticular — treat as polyarticular RF-negative",
      "Target: inactive disease (JADAS-27 ≤1 oligoarticular)",
      "Leg length discrepancy: physio, orthotics; rarely epiphysiodesis",
    ],
    monitoring: ["JADAS-27 every visit", "Uveitis slit-lamp (q3m if high risk)", "CBC + LFT monthly on MTX", "Growth assessment", "DEXA if steroids"],
    drugs: ["Naproxen", "Ibuprofen", "Triamcinolone hexacetonide", "Methotrexate + folic acid", "Adalimumab", "Abatacept"],
    emergency_flags: ["Sudden red painful eye — anterior uveitis flare", "Fever + swelling — rule out septic arthritis", "Acute band keratopathy (visual loss)"],
    prognosis: "~50% achieve remission off medications. Extended subtype — poorer prognosis, 70% active at 10y. Uveitis accounts for major morbidity.",
    refs: [
      { title: "ACR JIA Treatment Recommendations 2022", url: "https://www.rheumatology.org/" },
      { title: "PRINTO JIA Classification 2023", url: "https://www.printo.it/" },
    ],
    evidence_grade: "Strong",
    last_updated: "2024-02",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "jia_poly_rfneg",
    name: "JIA — Polyarticular RF−",
    category: "JIA",
    urgency: "high",
    icd: "M08.3",
    guideline: "ACR 2022 JIA Recommendations",
    tags: ["Polyarticular", "MTX", "TNFi", "Biologic"],
    variants: ["Symmetric small joint (adult RA-like)", "Large joint involvement", "Cervical spine + TMJ variant"],
    overview: "≥5 joints in first 6 months, RF negative. More aggressive than oligoarticular. Bimodal age: 1–3y and 8–12y. Cervical spine/TMJ at risk.",
    classification: "ILAR: ≥5 joints in first 6 months, RF negative on two tests ≥3 months apart",
    diagnostic_criteria: [
      "≥5 joints in first 6 months",
      "Negative RF on two tests ≥3 months apart",
      "Onset <16y, duration ≥6 weeks",
      "Exclude: psoriasis, ERA features, family history SpA, HLA-B27 positivity",
    ],
    flowchart: [
      "Confirm: ≥5 joints, RF−, ANA (30% positive), X-ray hands/feet for erosions",
      "Early aggressive therapy: MTX 15 mg/m² SC weekly + folic acid (do not delay)",
      "Bridge therapy: short course oral prednisolone if severe (0.5 mg/kg/day, taper in 4–6 weeks)",
      "Reassess at 3 months: if JADAS-27 >3.8 (low disease), escalate",
      "Add biologic at 3–6 months: etanercept, adalimumab, or abatacept",
      "TMJ/cervical spine involvement: MRI, anaesthesiology pre-intubation warning",
    ],
    decision_nodes: [
      { q: "Active disease despite 3 months MTX?", yes: "Add TNFi (etanercept/adalimumab) — combination therapy", no: "Continue MTX, target JADAS low activity" },
      { q: "TNFi failure (2nd TNFi inadequate)?", yes: "Switch mechanism: abatacept or tocilizumab", no: "Maintain TNFi + MTX combination" },
    ],
    key_points: [
      "Early MTX (15 mg/m² SC weekly) — do not delay. Add folic acid 5 mg/week",
      "Target: JADAS-27 ≤3.8 (low activity) within 6 months",
      "Cervical spine disease: risk of atlantoaxial subluxation — pre-anaesthesia imaging",
      "TNFi (etanercept or adalimumab) at 3–6 months if inadequate MTX response",
      "Abatacept (CTLA4-Ig) or tocilizumab (IL-6i) for TNFi failure",
      "Uveitis screening: q6 months if ANA−; more frequent if ANA+",
    ],
    monitoring: ["JADAS-27 each visit", "DAS28", "CBC + LFT q4–8 weeks on MTX", "DEXA if on steroids", "X-ray hands/feet yearly (erosion surveillance)"],
    drugs: ["Methotrexate", "Folic acid", "Prednisolone (bridge)", "Etanercept", "Adalimumab", "Abatacept", "Tocilizumab"],
    emergency_flags: ["C-spine instability (neck pain + neurology)", "MAS in acute flare", "Infection on biologic"],
    prognosis: "~60% still active at adulthood. Early aggressive therapy improves remission rates.",
    refs: [{ title: "ACR JIA 2022", url: "https://www.rheumatology.org/" }],
    evidence_grade: "Strong",
    last_updated: "2024-01",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "jia_systemic",
    name: "sJIA — Systemic JIA",
    category: "JIA",
    urgency: "critical",
    icd: "M08.2",
    guideline: "ACR 2022 + PRINTO sJIA Guidelines",
    tags: ["MAS Risk", "IL-1", "IL-6", "Anakinra", "Tocilizumab", "Emergency"],
    variants: ["Systemic-predominant (fever-dominant)", "Arthritis-predominant", "Macrophage Activation Syndrome (MAS)"],
    overview: "Quotidian fever + arthritis + one or more: salmon rash, lymphadenopathy, hepatosplenomegaly, serositis. MAS life-threatening complication in up to 10%.",
    classification: "ILAR: arthritis ≥6 weeks, quotidian fever ≥2 weeks + ≥1 of: rash, lymphadenopathy, hepatosplenomegaly, serositis",
    diagnostic_criteria: [
      "Quotidian (once-daily) fever ≥38.5°C for ≥2 weeks",
      "Arthritis (may lag fever by weeks–months)",
      "Salmon-colored evanescent rash (during fever)",
      "Lymphadenopathy, hepatosplenomegaly, serositis",
      "Elevated ferritin, S100A8/9 proteins",
    ],
    flowchart: [
      "Suspect sJIA: quotidian fever + rash + arthralgia — exclude infection, malignancy",
      "Labs: CBC, ferritin (daily), LFT, ESR, CRP, blood cultures, LDH, triglycerides",
      "Ferritin >500 rising rapidly — MAS alarm: stop and reassess",
      "NSAIDs ± bridging steroids for mild-moderate (prednisolone 0.5–1 mg/kg/day)",
      "Early IL-1 inhibitor: anakinra SC 2–4 mg/kg/day (preferred for MAS risk) OR canakinumab",
      "IL-6 inhibitor alternative: tocilizumab IV q2–4 weeks",
      "MAS: IV methylprednisolone 30 mg/kg/day × 3 + IV anakinra escalating + cyclosporin",
    ],
    decision_nodes: [
      { q: "Ferritin >684 AND any: plt ≤181, AST >48, TG >156, fibrinogen ≤360?", yes: "MAS — emergency protocol: IV steroids + IV anakinra + cyclosporin", no: "Active sJIA — start IL-1/IL-6 inhibitor" },
      { q: "Active systemic disease (fever/rash) despite IL-1i?", yes: "Switch to tocilizumab (IL-6i) or escalate anakinra dose", no: "Taper steroids, maintain biologic" },
    ],
    key_points: [
      "AVOID methotrexate in active systemic phase — ineffective, may worsen",
      "IL-1 inhibitors first-line biologic: anakinra (daily SC, flexible dosing) or canakinumab (q8 weeks)",
      "Tocilizumab (IL-6i): alternative first-line for sJIA",
      "MAS criteria 2016: ferritin >684 + any 2 of: plt ≤181k, AST >48, TG >156, fibrinogen ≤360",
      "IV methylprednisolone + cyclosporin 3–5 mg/kg IV + IV anakinra for MAS",
      "Ferritin falling ESR paradox = MAS alarm",
      "Echo for pericarditis if chest symptoms",
      "Lung disease (ILD) emerging complication — tocilizumab preferred if ILD",
    ],
    monitoring: ["Daily ferritin in flares", "CBC, LFT, fibrinogen, triglycerides", "JADAS-27", "Echo (pericarditis)", "HRCT if respiratory symptoms"],
    drugs: ["NSAIDs", "Prednisolone", "Anakinra (IL-1Ra)", "Canakinumab (IL-1β)", "Tocilizumab (IL-6i)", "Cyclosporin (MAS)", "IV methylprednisolone"],
    emergency_flags: ["Ferritin >10,000 — ICU admission", "Pericardial effusion with tamponade", "DIC + multiorgan failure", "Pulmonary hypertension"],
    prognosis: "Monophasic course in 40–50%. Polycyclic/persistent in remainder. MAS mortality 8–22% if untreated.",
    refs: [
      { title: "ACR sJIA 2022", url: "https://www.rheumatology.org/" },
      { title: "Ravelli MAS Criteria 2016", url: "https://pubmed.ncbi.nlm.nih.gov/26314539/" },
    ],
    evidence_grade: "Strong",
    last_updated: "2024-03",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "jia_era",
    name: "JIA — Enthesitis-Related (ERA)",
    category: "JIA",
    urgency: "medium",
    icd: "M08.1",
    guideline: "ACR 2022 + ASAS/EULAR SpA",
    tags: ["HLA-B27", "Enthesitis", "Sacroiliitis", "TNFi", "IL-17"],
    variants: ["Peripheral ERA", "Axial ERA (juvenile AS)", "Mixed axial + peripheral"],
    overview: "Arthritis + enthesitis in males >8y. HLA-B27 positive in ~80%. Risk of ankylosing spondylitis in adulthood. Acute anterior uveitis (painful, unlike oligoarticular).",
    flowchart: [
      "Confirm ERA: arthritis/enthesitis + ≥2 of: SI joint tenderness, IBP, HLA-B27+, acute uveitis, family history SpA",
      "Imaging: X-ray pelvis, MRI SI joints (STIR) for sacroiliitis",
      "NSAIDs: indomethacin 2–3 mg/kg/day (most effective for back/enthesitis)",
      "Sulfasalazine 30–50 mg/kg/day for peripheral arthritis",
      "TNFi (adalimumab, etanercept) for axial disease or NSAID-refractory",
      "IL-17A inhibitor (secukinumab): NSAID/TNFi failure — JUNIPERA trial",
    ],
    decision_nodes: [
      { q: "Axial disease (sacroiliitis on MRI) present?", yes: "TNFi first-line (adalimumab preferred for HLA-B27 uveitis risk)", no: "Sulfasalazine + NSAIDs for peripheral disease" },
      { q: "TNFi failure for axial ERA?", yes: "Secukinumab (IL-17Ai) or another TNFi", no: "Continue TNFi + physical therapy" },
    ],
    key_points: [
      "NSAIDs (indomethacin) critical for back pain/enthesitis — use regularly",
      "MRI SI joints (STIR) to detect early sacroiliitis before X-ray changes",
      "HLA-B27 positive — increased uveitis and progression risk",
      "TNFi required for significant axial disease",
      "Secukinumab (IL-17Ai) — JUNIPERA trial: approved for juvenile nr-axSpA",
      "Physical therapy: core strengthening, posture — essential",
      "Acute painful red eye: anterior uveitis — ophthalmology same day",
    ],
    monitoring: ["BASDAI/BASFI scores", "MRI SI joints annually", "Uveitis monitoring", "ASDAS-CRP"],
    drugs: ["Indomethacin", "Naproxen", "Sulfasalazine", "Adalimumab", "Etanercept", "Secukinumab"],
    emergency_flags: ["Acute painful red eye — anterior uveitis", "Cord compression from C-spine/thoracic disease"],
    prognosis: "25–50% progress to adult AS. Early TNFi therapy may prevent structural damage.",
    refs: [{ title: "ACR JIA ERA 2022", url: "https://www.rheumatology.org/" }],
    evidence_grade: "Strong",
    last_updated: "2024-01",
    review_status: "EXPERT_REVIEWED",
  },

  // ── SLE ──────────────────────────────────────────────────────────────────
  {
    id: "pediatric_sle",
    name: "Pediatric SLE",
    category: "SLE",
    urgency: "critical",
    icd: "M32.9",
    guideline: "ACR/EULAR 2019 SLE + EULAR pSLE 2023",
    tags: ["ANA", "dsDNA", "HCQ", "MMF", "Belimumab", "Nephritis"],
    variants: ["Nephritis-dominant", "Haematologic-dominant", "Neuropsychiatric", "Mucocutaneous-dominant"],
    overview: "Multisystem autoimmune. More aggressive in children (60–80% nephritis vs 30–40% adults). ACR/EULAR 2019 criteria. HCQ mandatory for ALL.",
    classification: "ACR/EULAR 2019: ANA ≥1:80 (entry) + weighted domain criteria ≥10 points",
    diagnostic_criteria: [
      "ANA ≥1:80 — entry criterion",
      "Anti-dsDNA, anti-Sm, antiphospholipid antibodies",
      "Low C3/C4",
      "Weighted criteria across 8 domains (constitutional, haem, neuro, mucocutaneous, serosal, MSK, renal, immunologic)",
      "≥10 points = SLE diagnosis",
    ],
    flowchart: [
      "ANA positive >1:80: confirm with anti-dsDNA, anti-Sm, C3/C4, antiphospholipid panel",
      "Urine PCR + microscopy — screen for nephritis even if asymptomatic",
      "Start hydroxychloroquine 5 mg/kg/day (max 400 mg) IMMEDIATELY — all patients",
      "Mild (skin/joints): low-dose prednisolone + HCQ",
      "Moderate–severe: prednisolone 1–2 mg/kg/day + MMF or AZA",
      "Nephritis: renal biopsy MANDATORY — ISN/RPS classification drives treatment",
      "Class III/IV: IV MP pulses → MMF 2–3 g/day (or Euro-lupus CYC) + HCQ",
      "Incomplete response at 6m: add belimumab (anti-BLyS) or switch induction",
    ],
    decision_nodes: [
      { q: "Urine PCR >0.5 or active urine sediment?", yes: "Renal biopsy — mandatory for ISN/RPS classification", no: "Non-renal SLE pathway" },
      { q: "Class III or IV lupus nephritis?", yes: "IV methylprednisolone + MMF (preferred) or Euro-lupus CYC. Add voclosporin if available.", no: "Class V: MMF + ACEi. Class I/II: HCQ + supportive" },
    ],
    key_points: [
      "HCQ 5 mg/kg/day mandatory for ALL pSLE patients — reduces flares and mortality",
      "Renal biopsy mandatory for any renal involvement — ISN/RPS guides all therapy",
      "Class III/IV induction: MMF 2–3 g/day preferred over NIH CYC in pediatric SLE",
      "Maintenance: MMF 1–2 g/day + HCQ",
      "Belimumab (anti-BLyS): approved for pSLE ≥5y — BLISS-PEDIATRIC trial",
      "Targets: PCR <0.5, stable GFR, normalising C3/C4, falling dsDNA",
      "SLEDAI-2K every visit — guide therapy escalation/de-escalation",
      "Sunscreen, vitamin D, calcium supplementation mandatory",
      "Ophthalmology annually for HCQ maculopathy (after 5 years HCQ)",
    ],
    monitoring: ["SLEDAI-2K", "Anti-dsDNA, C3/C4 q3 months", "Urine PCR monthly (nephritis)", "BP control", "CBC, LFT, creatinine", "HCQ eye review annually"],
    drugs: ["Hydroxychloroquine", "Prednisolone", "Methylprednisolone IV", "MMF", "Azathioprine", "Cyclophosphamide", "Belimumab", "Rituximab", "Voclosporin"],
    emergency_flags: ["NPSLE — seizure/psychosis", "Catastrophic APS", "Diffuse alveolar haemorrhage", "Severe thrombocytopenia <20k", "Rapidly rising creatinine + haematuria"],
    prognosis: "Pediatric SLE more aggressive; 20% develop CKD. Mortality 3× adult SLE. HCQ dramatically improves outcomes.",
    refs: [
      { title: "ACR/EULAR SLE 2019 Classification Criteria", url: "https://www.rheumatology.org/" },
      { title: "EULAR pSLE Recommendations 2023", url: "https://www.eular.org/" },
    ],
    evidence_grade: "Strong",
    last_updated: "2024-04",
    review_status: "EXPERT_REVIEWED",
  },

  // ── VASCULITIS ────────────────────────────────────────────────────────────
  {
    id: "kawasaki",
    name: "Kawasaki Disease",
    category: "Vasculitis",
    urgency: "critical",
    icd: "M30.3",
    guideline: "AHA 2017 Scientific Statement + JCS 2024",
    tags: ["IVIG", "Aspirin", "Coronary Aneurysm", "Echo", "Emergency"],
    variants: ["Complete KD (≥4/5 features)", "Incomplete KD (2–3 features + labs/echo)", "Refractory KD (IVIG-resistant)"],
    overview: "Acute medium vessel vasculitis. Predominantly <5y. Coronary artery aneurysm (CAA) risk untreated ~25%. IVIG + aspirin remain cornerstones.",
    diagnostic_criteria: [
      "Fever ≥5 days + ≥4 principal features:",
      "1. Bilateral non-purulent conjunctival injection",
      "2. Polymorphous rash",
      "3. Strawberry tongue / cracked lips / oral erythema",
      "4. Extremity changes (erythema/edema → periungual desquamation)",
      "5. Cervical lymphadenopathy ≥1.5cm (usually unilateral)",
      "Incomplete KD: fever ≥5d + 2–3 features + supporting labs or echo",
    ],
    flowchart: [
      "Fever ≥5 days: assess all 5 KD features; check echo if ≥3 features or CRP/ESR elevated",
      "Labs: CBC (WBC >15k, plt >450k after d7), CRP ≥3 mg/dL, albumin ≤3g/dL, ALT elevated, anaemia, urine WBC >10/hpf",
      "Echo at diagnosis: coronary arteries Z-score — LCA and RCA",
      "IVIG 2 g/kg over 8–12 hours — single dose (within 10 days of fever onset)",
      "Aspirin 80–100 mg/kg/day (antipyretic dose) until afebrile 48–72h",
      "Then aspirin 3–5 mg/kg/day (antiplatelet dose) for 4–6 weeks (if no CAA) or lifelong",
      "Repeat echo at 2 weeks + 6–8 weeks",
    ],
    decision_nodes: [
      { q: "Fever persists/recurs ≥36h after IVIG?", yes: "IVIG-resistant: second IVIG 2g/kg OR infliximab 5 mg/kg OR methylprednisolone 30 mg/kg IV × 3", no: "IVIG-responsive: continue low-dose aspirin, echo surveillance" },
      { q: "Giant CAA (Z ≥10 or diameter >8mm)?", yes: "Lifelong anticoagulation + antiplatelet + cardiology; avoid NSAIDs; restrict activity", no: "Standard follow-up per Z-score category" },
    ],
    key_points: [
      "IVIG 2 g/kg as SINGLE dose within 10 days — reduces CAA from 25% to <5%",
      "IVIG given after day 10 still indicated if fever/inflammation persists",
      "Kobayashi score ≥5: add IV methylprednisolone to IVIG (Japanese high-risk criteria)",
      "Infliximab 5 mg/kg: equivalent to second IVIG for refractory KD",
      "Echo timing: diagnosis, 2 weeks, 6–8 weeks — all mandatory",
      "Z-score ≥2.5: coronary dilation; ≥10 or >8mm: giant aneurysm (anticoagulate)",
      "MIS-C overlap: post-COVID hyperinflammatory state — similar but older, more shock",
      "Cyclosporin for refractory cases (Japan data)",
    ],
    monitoring: ["Echo at diagnosis/2w/6–8w", "CBC, CRP, ESR, LFT, platelet trend", "Aspirin levels if high-dose", "Cardiology follow-up"],
    drugs: ["IVIG 2g/kg", "Aspirin (high-dose then low-dose)", "Methylprednisolone IV", "Infliximab", "Cyclosporin (refractory)"],
    emergency_flags: ["Myocarditis/cardiogenic shock", "Giant coronary aneurysm with thrombosis", "MAS overlap (ferritin rising)", "Coronary artery occlusion"],
    prognosis: "Excellent if treated early. Untreated: 25% CAA. Giant aneurysm: risk of MI in adulthood.",
    refs: [
      { title: "AHA KD Scientific Statement 2017", url: "https://www.ahajournals.org/doi/10.1161/CIR.0000000000000484" },
    ],
    evidence_grade: "Strong",
    last_updated: "2024-02",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "igav",
    name: "IgA Vasculitis (IgAV / HSP)",
    category: "Vasculitis",
    urgency: "high",
    icd: "D69.0",
    guideline: "EULAR/PRINTO/PReS 2010 Criteria + SHARE 2019",
    tags: ["Purpura", "IgAN Pattern", "Nephritis", "Self-limiting", "SHARE"],
    variants: ["Skin-limited IgAV", "IgAV with GI involvement", "IgAV nephritis (IgAVN)", "Severe/crescentic nephritis"],
    overview: "Most common vasculitis in children. Palpable purpura + arthritis/abdominal pain/nephritis. IgA deposition in vessel walls. Nephritis in 40–60%.",
    diagnostic_criteria: [
      "Mandatory: palpable purpura (or petechiae) in lower limb predominant distribution",
      "Plus ≥1 of: abdominal pain, histopathology (IgA deposits), arthritis/arthralgia, renal involvement (haematuria/proteinuria)",
      "EULAR/PRINTO/PReS 2010 classification",
    ],
    flowchart: [
      "Confirm purpura (non-thrombocytopenic) + urine dipstick/PCR at diagnosis",
      "CBC (normal platelets excludes ITP), coagulation screen, ANA, ANCA to exclude mimics",
      "Mild IgAV (skin + arthralgia): supportive, NSAIDs, hydration",
      "GI involvement: prednisolone 1 mg/kg/day for severe abdominal pain (intussusception watch)",
      "Renal monitoring: urine dipstick weekly × 4–6 weeks; PCR if dipstick positive",
      "IgAV nephritis with PCR >1.0: ACE inhibitor + consider biopsy",
      "Nephrotic/nephritic presentation: biopsy + steroids ± azathioprine/MMF",
      "Crescentic nephritis: cyclophosphamide + steroids (ECOG-based protocol)",
    ],
    decision_nodes: [
      { q: "Urine PCR >0.5 or haematuria + proteinuria?", yes: "IgAV nephritis — start ACEi, refer nephrology, consider biopsy", no: "Monitor urine weekly for 6 weeks — low renal risk" },
      { q: "Severe IgAV nephritis (nephrotic or crescentic)?", yes: "Biopsy + prednisolone + cyclophosphamide or MMF (ECOG protocol)", no: "ACEi + steroids for moderate nephritis" },
    ],
    key_points: [
      "Purpura in non-thrombocytopenic child: IgAV first diagnosis",
      "Urine monitoring for 6 weeks after presentation — nephritis can be delayed",
      "GI: steroids (prednisolone 1 mg/kg/day) for severe abdominal pain — NOT preventive for nephritis",
      "IgAV nephritis (IgAVN): managed like IgA nephropathy",
      "ACEi for persistent proteinuria (PCR >0.5)",
      "Crescentic nephritis: cyclophosphamide-based protocol",
      "Orchitis in males: watch for torsion",
      "Recurrence in 30–50% — usually milder",
    ],
    monitoring: ["Urine dipstick weekly × 6 weeks", "PCR if positive", "BP monitoring", "Renal function", "BVAS for activity"],
    drugs: ["NSAIDs", "Prednisolone", "ACE inhibitor", "Azathioprine", "MMF", "Cyclophosphamide"],
    emergency_flags: ["Intussusception (acute abdomen)", "Scrotal pain (orchitis/torsion)", "Crescentic nephritis — urgent biopsy", "CNS vasculitis (seizure/stroke)"],
    prognosis: "90% self-resolve. Long-term renal risk: <5% ESRD overall; higher with severe nephritis.",
    refs: [
      { title: "SHARE IgAV Management 2019", url: "https://www.eular.org/" },
      { title: "EULAR/PRINTO/PReS Criteria 2010", url: "https://www.printo.it/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-01",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "anca_vasculitis",
    name: "ANCA-Associated Vasculitis (GPA/MPA)",
    category: "Vasculitis",
    urgency: "critical",
    icd: "M31.3",
    guideline: "ACR/EULAR AAV 2022 + KDIGO 2021",
    tags: ["ANCA", "Rituximab", "Cyclophosphamide", "RPGN", "Renal Biopsy"],
    variants: ["GPA (PR3-ANCA, upper/lower respiratory + renal)", "MPA (MPO-ANCA, renal + pulmonary)", "Pauci-immune crescentic GN"],
    overview: "Rare but severe in children. ANCA-associated necrotizing vasculitis. PR3-ANCA = GPA; MPO-ANCA = MPA. Rapidly progressive GN and/or pulmonary haemorrhage.",
    flowchart: [
      "EMERGENCY: haematuria + proteinuria + rising creatinine + ANCA positive",
      "Urgent renal biopsy — pauci-immune necrotizing crescentic GN",
      "PR3-ANCA (GPA): check sinuses, chest CT for granulomas, ENT involvement",
      "Induction: rituximab 375 mg/m² weekly × 4 OR pulse cyclophosphamide + IV methylprednisolone",
      "Plasmapheresis: if creatinine >500 μmol/L or diffuse alveolar haemorrhage",
      "Prednisolone 1 mg/kg/day (max 60 mg) — taper over 6 months",
      "Maintenance: rituximab 375 mg/m² q6 months × 2 years (preferred) OR azathioprine",
    ],
    decision_nodes: [
      { q: "Creatinine >500 μmol/L or diffuse alveolar haemorrhage (DAH)?", yes: "Plasmapheresis + rituximab/CYC + IV steroids — ICU", no: "Rituximab induction (preferred) or pulse CYC + steroids" },
      { q: "PR3-ANCA (GPA subtype)?", yes: "Rituximab preferred — lower relapse rate vs MPO", no: "MPO-ANCA (MPA): rituximab or CYC equally effective" },
    ],
    key_points: [
      "Urgent renal biopsy + ANCA testing simultaneously — do not delay treatment",
      "Rituximab (RTX) preferred induction for children — non-inferior to CYC, less gonadotoxicity",
      "Cyclophosphamide: avoid if possible in young females (gonadal toxicity)",
      "Plasmapheresis: Cr >500 μmol/L, pulmonary haemorrhage",
      "Maintenance: RTX 375 mg/m² every 6 months × 2 years",
      "Monitor ANCA titres — rising titre may predict relapse",
      "TMP-SMX prophylaxis during induction (PJP prevention)",
      "Nephrology co-management mandatory — CKD risk significant",
    ],
    monitoring: ["BVAS score", "ANCA titres q3 months", "Urine PCR monthly", "Creatinine trend", "Chest imaging for GPA", "CBC + LFT"],
    drugs: ["Rituximab", "Cyclophosphamide", "Methylprednisolone IV", "Prednisolone", "Azathioprine (maintenance)", "TMP-SMX (prophylaxis)"],
    emergency_flags: ["Pulmonary haemorrhage (DAH) — ICU", "Rapidly progressive GN (dialysis risk)", "Subglottic stenosis (GPA)", "Orbital pseudotumour (GPA)"],
    prognosis: "Relapse rate 50% in GPA at 5y. PR3-ANCA > MPO-ANCA relapse risk. Rituximab maintenance reduces relapses.",
    refs: [
      { title: "ACR/EULAR AAV Guidelines 2022", url: "https://www.rheumatology.org/" },
      { title: "KDIGO 2021 GN Guideline", url: "https://kdigo.org/guidelines/gd/" },
    ],
    evidence_grade: "Strong",
    last_updated: "2024-04",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "mis_c",
    name: "MIS-C (Multisystem Inflammatory Syndrome)",
    category: "Vasculitis",
    urgency: "critical",
    icd: "M35.8",
    guideline: "WHO MIS-C Definition 2020 + AHA 2021",
    tags: ["Post-COVID", "IVIG", "Shock", "Coronary", "KD-like"],
    variants: ["KD-like MIS-C", "Shock-predominant MIS-C", "Gastrointestinal-predominant", "MAS-like MIS-C"],
    overview: "Post-COVID-19 hyperinflammatory syndrome. Fever + multisystem + SARS-CoV-2 evidence. More severe than KD — myocardial dysfunction, shock in 50%.",
    flowchart: [
      "Fever ≥3 days + 2+ systems + elevated CRP/ferritin/D-dimer + SARS-CoV-2 serology/PCR",
      "URGENT: ECG, echo, troponin, BNP/NT-proBNP — cardiac assessment",
      "Shock: IV fluids + inotropic support; ICU if haemodynamically unstable",
      "IVIG 2 g/kg over 8–12h (KD-like or elevated markers) — most patients",
      "IV methylprednisolone 2 mg/kg/day for cardiac dysfunction or shock",
      "Low-dose aspirin 3–5 mg/kg/day — KD-like features",
      "Anticoagulation: LMWH if CAA Z ≥2.5 or D-dimer markedly elevated",
      "IVIG-refractory: second IVIG or IV methylprednisolone escalation",
    ],
    decision_nodes: [
      { q: "Cardiogenic shock or severe cardiac dysfunction?", yes: "ICU + inotropes + IV MP (preferred over IVIG alone) + cardiology", no: "IVIG 2g/kg ± methylprednisolone — standard care" },
      { q: "Ferritin >1500 + cytopenias (MAS-like)?", yes: "IV anakinra for MAS-like features", no: "Standard IVIG + steroids protocol" },
    ],
    key_points: [
      "IVIG 2 g/kg + methylprednisolone 2 mg/kg/day — superior to IVIG alone (RECOVERY-PLUS data)",
      "Echo at diagnosis mandatory: coronary arteries + ventricular function",
      "Troponin + BNP monitoring during acute phase",
      "Aspirin 3–5 mg/kg/day until echo normal and inflammation resolves",
      "Most recover completely within 4–6 weeks",
      "Echo follow-up: 2 weeks + 6–8 weeks",
      "AKI occurs in ~30% — nephrology involvement if oliguria/rising creatinine",
      "Post-discharge: cardiology follow-up at 1–2 months",
    ],
    monitoring: ["Echo at diagnosis/2w/6–8w", "Troponin, BNP, ferritin, D-dimer", "CBC, CRP, fibrinogen", "ECG", "BP, urine output"],
    drugs: ["IVIG 2g/kg", "Methylprednisolone IV", "Aspirin low-dose", "Anakinra (MAS-like)", "Heparin/LMWH (anticoagulation)", "Inotropes (shock)"],
    emergency_flags: ["Cardiogenic shock", "Giant coronary aneurysm", "MAS (ferritin >10,000)", "AKI requiring RRT"],
    prognosis: "Most recover fully. Mortality <2% with appropriate management. Long-term cardiac outcomes generally excellent.",
    refs: [
      { title: "AHA MIS-C Scientific Statement 2021", url: "https://www.ahajournals.org/" },
      { title: "WHO MIS-C Case Definition 2020", url: "https://www.who.int/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-04",
    review_status: "EXPERT_REVIEWED",
  },

  // ── AUTOINFLAMMATORY ──────────────────────────────────────────────────────
  {
    id: "mas_hlh",
    name: "MAS / HLH",
    category: "Autoinflammatory",
    urgency: "critical",
    icd: "D76.1",
    guideline: "HLH-2004 Protocol + 2016 MAS-sJIA Criteria",
    tags: ["Ferritin >10k", "Cytokine Storm", "ICU", "Anakinra", "Emergency"],
    variants: ["sJIA-associated MAS", "SLE-associated MAS", "Infection-triggered HLH", "Primary HLH (familial)"],
    overview: "Macrophage Activation Syndrome = reactive HLH. Life-threatening cytokine storm. Unremitting fever + rapidly rising ferritin + pancytopenia + organ failure.",
    diagnostic_criteria: [
      "2016 MAS-sJIA criteria: Known/suspected sJIA + ferritin >684 + ≥2 of: plt ≤181k, AST >48, TG >156, fibrinogen ≤360",
      "HLH-2004: ≥5 of 8: fever, splenomegaly, cytopenias, hypertriglyceridaemia, hypofibrinogenaemia, haemophagocytosis (BM), low/absent NK, ferritin >500",
      "HScore calculator for probability estimation",
    ],
    flowchart: [
      "EMERGENCY: rising ferritin + cytopenias + fever — activate MAS protocol",
      "Daily labs: ferritin, CBC, LFT, fibrinogen, triglycerides, d-dimer, coagulation",
      "Bone marrow aspirate if diagnosis uncertain (haemophagocytosis)",
      "IV methylprednisolone 30 mg/kg/day (max 1g) × 3 days — immediately",
      "Cyclosporin 3–5 mg/kg IV — key for sJIA-MAS",
      "IV anakinra escalating: start 2 mg/kg SC/IV → escalate to 4–8 mg/kg IV if severe",
      "HLH-2004 protocol (etoposide) for primary HLH or non-responding MAS",
      "Ruxolitinib for refractory/life-threatening",
    ],
    decision_nodes: [
      { q: "Ferritin >10,000 and multiorgan failure?", yes: "ICU — IV methylprednisolone + IV anakinra + cyclosporin + haematology consult", no: "High-dose IV steroid + cyclosporin + monitor daily" },
      { q: "Primary HLH suspected (family history, young infant, no rheumatic trigger)?", yes: "HLH-2004 protocol + HLH gene panel + HSCT planning", no: "Secondary/reactive MAS — treat underlying trigger + immunosuppression" },
    ],
    key_points: [
      "Falling ESR despite active fever = MAS alarm sign",
      "IV methylprednisolone + IV cyclosporin: first-line combination for sJIA-MAS",
      "IV anakinra (escalating to 8 mg/kg) for refractory MAS — game changer",
      "Ruxolitinib: JAK1/2 inhibitor for refractory HLH",
      "IVIG for virus-triggered HLH",
      "DO NOT miss primary HLH: PRF1, UNC13D, STX11, STXBP2 — gene panel",
      "Allogeneic HSCT for primary HLH — only cure",
      "Trigger treatment: antivirals for EBV/CMV-HLH",
    ],
    monitoring: ["Daily ferritin", "Daily CBC, LFT, fibrinogen, TG", "Bone marrow", "Neurological status", "Organ function"],
    drugs: ["IV Methylprednisolone", "Cyclosporin IV", "IV Anakinra (escalating)", "Etoposide (HLH-2004)", "Ruxolitinib", "IVIG", "Dexamethasone"],
    emergency_flags: ["Ferritin >10,000 — ICU mandatory", "DIC + multiorgan failure", "CNS involvement (seizures)", "Pulmonary haemorrhage"],
    prognosis: "Untreated mortality >50%. With anakinra escalation and cyclosporin: survival >80% in sJIA-MAS.",
    refs: [
      { title: "Ravelli MAS-sJIA Criteria 2016", url: "https://pubmed.ncbi.nlm.nih.gov/26314539/" },
      { title: "HLH-2004 Protocol", url: "https://pubmed.ncbi.nlm.nih.gov/15793426/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-03",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "fmf",
    name: "FMF (Familial Mediterranean Fever)",
    category: "Autoinflammatory",
    urgency: "medium",
    icd: "E85.0",
    guideline: "Eurofever/PRINTO FMF Criteria 2019",
    tags: ["MEFV", "Colchicine", "IL-1", "Amyloid", "Renal Risk"],
    variants: ["Typical FMF (peritonitis/pleuritis)", "Arthritis-predominant", "FMF complicated by amyloidosis"],
    overview: "Most common hereditary periodic fever. MEFV gene. Autosomal recessive. Recurrent 12–72h fever attacks. Amyloidosis (AA) — major long-term renal risk.",
    flowchart: [
      "Recurrent fever attacks 12–72h + peritonitis/pleuritis/arthritis + ethnicity (Mediterranean, Middle East, Indian)",
      "MEFV gene sequencing — M694V most severe (amyloid risk)",
      "Exclude: appendicitis, septic arthritis, IBD, other periodic fever syndromes",
      "Start colchicine 0.5–2 mg/day (weight-based) — LIFELONG",
      "Target: attack-free or <1 attack/month",
      "If colchicine-resistant or intolerant: anakinra or canakinumab",
      "Annual urine protein — amyloid surveillance",
    ],
    decision_nodes: [
      { q: "≥1 attack/month despite colchicine maximum tolerated dose?", yes: "Colchicine-resistant: add anakinra 1–2 mg/kg/day or canakinumab 2 mg/kg q8w", no: "Maintain colchicine, annual SAA monitoring" },
      { q: "Proteinuria developing?", yes: "Renal biopsy — Congo red for AA amyloid; aggressive attack suppression + ACEi", no: "Annual urine PCR + SAA level monitoring" },
    ],
    key_points: [
      "Colchicine is curative-level treatment — start immediately, lifelong",
      "Target colchicine: complete attack prevention or SAA <10 mg/L between attacks",
      "M694V homozygous: highest amyloid risk — aggressive suppression mandatory",
      "Anakinra or canakinumab for colchicine-resistant FMF (FDA/EMA approved)",
      "Amyloidosis prevention: maintain SAA <10 mg/L",
      "Renal amyloidosis = nephrotic syndrome — ACEi + treat FMF aggressively",
      "Live vaccines: check before biologics",
      "TB screening before IL-1 inhibitors",
    ],
    monitoring: ["Attack diary", "SAA level (target <10 mg/L)", "Urine PCR annually", "Renal function", "Growth on colchicine"],
    drugs: ["Colchicine", "Anakinra", "Canakinumab", "Rilonacept"],
    emergency_flags: ["Nephrotic syndrome (amyloidosis)", "Severe peritonitis attack mimicking acute abdomen", "Cardiac tamponade (pericarditis)"],
    prognosis: "Excellent with colchicine. Amyloidosis risk dramatically reduced with adequate treatment.",
    refs: [
      { title: "Eurofever/PRINTO FMF Criteria 2019", url: "https://www.printo.it/" },
    ],
    evidence_grade: "Strong",
    last_updated: "2024-01",
    review_status: "EXPERT_REVIEWED",
  },

  // ── MYOSITIS ──────────────────────────────────────────────────────────────
  {
    id: "jdm",
    name: "Juvenile Dermatomyositis (JDM)",
    category: "Myositis",
    urgency: "high",
    icd: "M33.0",
    guideline: "ACR/EULAR 2017 IIM Classification + BSR JDM Guidelines",
    tags: ["Gottron", "Heliotrope", "Calcinosis", "ILD", "MTX", "IVIG"],
    variants: ["Classic JDM (skin + muscle)", "Amyopathic DM (skin-dominant)", "Overlap JDM (anti-Jo1, ILD)", "Calcinosis-predominant"],
    overview: "Inflammatory myopathy with pathognomonic skin findings. Gottron papules + heliotrope rash. Calcinosis in 30–70% if treatment delayed.",
    diagnostic_criteria: [
      "Pathognomonic: Gottron papules (extensor joints) and/or heliotrope rash",
      "Proximal muscle weakness (Gowers sign)",
      "Elevated muscle enzymes: CK, LDH, aldolase, AST",
      "MRI (STIR): muscle oedema/inflammation",
      "Myositis-specific antibodies (MSA) panel",
      "EMG/muscle biopsy if diagnosis uncertain",
    ],
    flowchart: [
      "Confirm: Gottron/heliotrope + proximal weakness + elevated CK/LDH/aldolase",
      "Myositis antibody panel: anti-MDA5, TIF1γ, NXP2, Mi-2, Jo-1",
      "Anti-MDA5 positive: urgent HRCT chest (rapidly progressive ILD risk)",
      "Induction: prednisolone 2 mg/kg/day (max 60 mg) + MTX 15 mg/m² weekly SC",
      "IV methylprednisolone pulses 30 mg/kg × 3 for severe disease",
      "IVIG 2 g/kg monthly for refractory or calcinosis management",
      "Cyclosporin for ILD or MTX-refractory",
      "Rituximab for severe refractory (RITS trial evidence)",
    ],
    decision_nodes: [
      { q: "Anti-MDA5 positive or respiratory symptoms?", yes: "Urgent HRCT + cyclosporin/rituximab for ILD — aggressive therapy", no: "Standard MTX + steroid induction" },
      { q: "Calcinosis progressive despite standard therapy?", yes: "IVIG 2g/kg monthly + consider bisphosphonates/colchicine for calcinosis", no: "Maintain IVIG support as needed" },
    ],
    key_points: [
      "Gottron papules + heliotrope rash: pathognomonic for JDM",
      "Photoprotection/sunscreen CRITICAL — sun exposure worsens disease activity",
      "Early aggressive treatment prevents calcinosis",
      "Anti-MDA5: rapidly progressive ILD risk — urgent HRCT and cyclosporin",
      "Anti-NXP2: severe muscle disease + calcinosis",
      "Anti-TIF1γ: older onset, photodistributed rash",
      "CMAS score: monitor muscle function every visit",
      "IVIG 2g/kg monthly: effective for refractory disease and calcinosis reduction",
      "Rituximab for refractory skin or muscle disease",
    ],
    monitoring: ["CMAS score each visit", "CK, LDH, aldolase", "HRCT chest (ILD surveillance)", "PFTs", "MRI muscle (STIR)", "Ophthalmology (calcinosis periorbital)"],
    drugs: ["Prednisolone", "Methylprednisolone IV", "Methotrexate", "IVIG", "Cyclosporin", "Rituximab", "Hydroxychloroquine (skin)"],
    emergency_flags: ["Respiratory failure (ILD/respiratory muscle weakness)", "Dysphagia (aspiration risk)", "Rapidly progressive calcinosis"],
    prognosis: "~50% monocyclic. Calcinosis main morbidity if treatment delayed. ILD-associated JDM: more severe course.",
    refs: [
      { title: "ACR/EULAR IIM Classification 2017", url: "https://www.rheumatology.org/" },
      { title: "BSR JDM Guidelines", url: "https://www.rheumatology.org.uk/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-02",
    review_status: "EXPERT_REVIEWED",
  },
];

export const RHEUM_CATEGORIES_V2 = ["All", "JIA", "SLE", "Vasculitis", "Myositis", "Autoinflammatory"];

export const URGENCY_CONFIG = {
  critical: { label: "🔴 Critical", color: "bg-red-100 text-red-800 border-red-300" },
  high: { label: "🟠 High Priority", color: "bg-amber-100 text-amber-800 border-amber-300" },
  medium: { label: "🔵 Standard", color: "bg-blue-100 text-blue-800 border-blue-300" },
};

export const CATEGORY_COLORS = {
  JIA: "bg-blue-100 text-blue-800",
  SLE: "bg-purple-100 text-purple-800",
  Vasculitis: "bg-red-100 text-red-800",
  Myositis: "bg-orange-100 text-orange-800",
  Autoinflammatory: "bg-amber-100 text-amber-800",
  Uveitis: "bg-teal-100 text-teal-800",
};