// ── Pediatric Rheumatology Drug Knowledge System ──────────────────────────

export const RHEUM_DRUGS = [
  {
    id: "mtx",
    name: "Methotrexate (MTX)",
    class: "DMARD",
    mechanism: "Folate antagonist — inhibits DHFR; anti-inflammatory via adenosine pathway at low doses",
    indications: ["JIA (all subtypes except sJIA)", "JDM", "SLE", "Uveitis (steroid-sparing)", "Vasculitis (maintenance)"],
    pediatric_dose: "10–15 mg/m² SC weekly (max 25 mg/week). SC preferred over PO for bioavailability and reduced GI side effects.",
    folic_acid: "5 mg PO once weekly (24–48h after MTX) — mandatory to reduce toxicity",
    monitoring: { schedule: "CBC + LFT + creatinine monthly × 3, then q3 months", targets: "AST/ALT <2× ULN; WBC >3.5k; ANC >1.5k" },
    toxicities: ["Nausea/vomiting (most common — mitigated by folic acid)", "Hepatotoxicity (LFT elevation)", "Myelosuppression", "Pulmonary toxicity (rare)", "Mouth ulcers"],
    contraindications: ["Pregnancy (teratogenic)", "Active hepatitis", "Severe renal impairment (eGFR <30)", "Active serious infection"],
    renal_adjustment: "Reduce dose 50% if GFR 30–50. Avoid if GFR <30.",
    live_vaccines: "AVOID all live vaccines (varicella, MMR, yellow fever) during therapy",
    tb_screening: "Not routinely required (low immunosuppression level)",
    pregnancy: "Highly teratogenic — stop ≥3 months before conception. Women of child-bearing age: contraception mandatory.",
    evidence_grade: "Strong (1A)",
    refs: ["ACR JIA 2022 Guidelines"],
  },
  {
    id: "hcq",
    name: "Hydroxychloroquine (HCQ)",
    class: "Antimalarial / DMARD",
    mechanism: "Blocks TLR7/9 signalling; interferes with lysosomal acidification and antigen processing; anti-inflammatory",
    indications: ["ALL pSLE patients (mandatory)", "JIA (mild)", "Sjögren's overlap"],
    pediatric_dose: "5 mg/kg/day PO (max 400 mg/day). Do NOT exceed 5 mg/kg — reduces maculopathy risk.",
    monitoring: { schedule: "Annual ophthalmology from year 5 (earlier if high risk)", targets: "No maculopathy on OCT" },
    toxicities: ["HCQ maculopathy (dose and duration dependent)", "GI intolerance", "Skin hyperpigmentation (rare)", "Hemolysis in G6PD deficiency"],
    contraindications: ["G6PD deficiency (relative)", "Pre-existing maculopathy"],
    renal_adjustment: "No dose adjustment needed for mild-moderate CKD; use with caution in severe CKD",
    live_vaccines: "Safe — no restrictions",
    pregnancy: "SAFE in pregnancy — continue in SLE (reduces flares)",
    evidence_grade: "Strong (1A) for SLE",
    refs: ["ACR/EULAR SLE 2019", "EULAR pSLE 2023"],
  },
  {
    id: "azathioprine",
    name: "Azathioprine (AZA)",
    class: "DMARD / Immunosuppressant",
    mechanism: "Purine analogue — inhibits DNA synthesis; depletes T and B lymphocytes",
    indications: ["SLE maintenance", "JDM", "Vasculitis maintenance (ANCA)", "JIA (second-line DMARD)"],
    pediatric_dose: "1–3 mg/kg/day PO in 1–2 divided doses",
    monitoring: { schedule: "CBC + LFT monthly × 3, then q3 months", targets: "WBC >3.5k; no hepatotoxicity" },
    toxicities: ["Myelosuppression (most important)", "GI intolerance", "Hepatotoxicity", "Pancreatitis (rare)", "Increased lymphoma risk (long-term)"],
    contraindications: ["Active serious infection", "Concurrent allopurinol use (TPMT interaction — fatal)", "Severe TPMT deficiency"],
    tpmt_testing: "TPMT genotype/phenotype BEFORE starting — TPMT-deficient: severe myelosuppression risk",
    renal_adjustment: "Reduce dose 50% if GFR <30",
    live_vaccines: "AVOID live vaccines",
    pregnancy: "Can be continued in pregnancy (safest DMARD for SLE pregnancy)",
    evidence_grade: "Moderate (2B)",
    refs: ["ACR/EULAR SLE 2019"],
  },
  {
    id: "mmf",
    name: "Mycophenolate Mofetil (MMF)",
    class: "Immunosuppressant",
    mechanism: "Selective inhibitor of IMPDH — blocks de novo purine synthesis in lymphocytes",
    indications: ["Lupus nephritis (induction + maintenance)", "JDM refractory", "IgAV nephritis", "ANCA vasculitis maintenance"],
    pediatric_dose: "600 mg/m² PO BID (max 2–3 g/day for induction, 1–2 g/day maintenance)",
    monitoring: { schedule: "CBC + LFT q4–8 weeks initially, then q3 months", targets: "WBC >3k; no GI intolerance" },
    toxicities: ["GI (diarrhoea, nausea — most common)", "Myelosuppression", "Increased infection risk", "Teratogenicity"],
    contraindications: ["Pregnancy (teratogenic — REMS program)", "Active serious infection"],
    renal_adjustment: "No dose adjustment needed in CKD (not renally cleared); use caution in severe impairment",
    live_vaccines: "AVOID live vaccines",
    pregnancy: "CONTRAINDICATED — teratogenic (limb, ear defects). Stop 6 weeks before conception.",
    evidence_grade: "Strong (1B) for lupus nephritis",
    refs: ["ACR/EULAR LN 2019", "EULAR pSLE 2023"],
  },
  {
    id: "cyclophosphamide",
    name: "Cyclophosphamide (CYC)",
    class: "Alkylating Agent / Immunosuppressant",
    mechanism: "DNA cross-linking alkylating agent — depletes rapidly dividing lymphocytes",
    indications: ["Lupus nephritis III/IV (induction — Euro-lupus or NIH protocol)", "ANCA vasculitis induction", "IgAV severe nephritis", "MAS refractory"],
    pediatric_dose: {
      iv_pulse: "Euro-lupus: 500 mg IV q2 weeks × 6 doses. NIH: 500–1000 mg/m² IV q3–4 weeks × 6",
      oral: "1.5–2 mg/kg/day PO (rarely used in children)"
    },
    monitoring: { schedule: "CBC d10 after each pulse; urinalysis monthly; LFT", targets: "Nadir WBC >2k; no haemorrhagic cystitis; no haematuria" },
    bladder_protection: "IV mesna or hyperhydration (2–3L/m²/day) to prevent haemorrhagic cystitis",
    toxicities: ["Myelosuppression", "Haemorrhagic cystitis (mesna prophylaxis)", "Gonadal toxicity (preserve fertility pre-treatment)", "Secondary malignancy (long-term)", "Nausea/vomiting"],
    contraindications: ["Active serious infection", "Severe cytopenias"],
    renal_adjustment: "Reduce dose if GFR <50; avoid if GFR <10",
    live_vaccines: "AVOID absolutely",
    pregnancy: "CONTRAINDICATED — teratogenic, fetotoxic",
    fertility_preservation: "MANDATORY: discuss oocyte/sperm cryopreservation before starting in adolescents",
    evidence_grade: "Strong (1A) for severe LN and ANCA",
    refs: ["ACR/EULAR LN 2019", "KDIGO 2021 GN"],
  },
  {
    id: "rituximab",
    name: "Rituximab (RTX)",
    class: "Anti-CD20 B-cell depleting biologic",
    mechanism: "Chimeric anti-CD20 monoclonal antibody — depletes B cells via ADCC, complement, apoptosis",
    indications: ["ANCA vasculitis (induction + maintenance)", "Refractory SLE/lupus nephritis", "JDM refractory", "IgG4-related disease", "Refractory JIA-uveitis"],
    pediatric_dose: "375 mg/m² IV weekly × 4 (induction) OR 1 g IV × 2 doses (2 weeks apart). Maintenance: 375 mg/m² q6 months.",
    premedication: "IV methylprednisolone 100 mg + antihistamine + paracetamol — 30 min before each infusion",
    monitoring: { schedule: "CD19/CD20 B-cell count, immunoglobulins q3–6 months; CBC, LFT", targets: "B-cell depletion confirmed; IgG >5 g/L" },
    toxicities: ["Infusion reactions (first dose most common)", "Hypogammaglobulinaemia (IgG <4 g/L — IVIG replacement)", "Increased infection risk (particularly PJP, CMV)", "PML (rare, monitor for neurological symptoms)"],
    contraindications: ["Active serious infection", "HBV (hepatitis B reactivation — screen and prophylax)", "Severe hypogammaglobulinaemia"],
    hbv_screening: "HBsAg + anti-HBc MANDATORY before RTX. If positive: entecavir prophylaxis for duration + 12 months after",
    tb_screening: "TST/IGRA before RTX — treat latent TB before starting",
    live_vaccines: "AVOID. Give all vaccines ≥4 weeks before RTX if possible. No live vaccines ≤6 months after.",
    pregnancy: "Avoid — neonatal B-cell depletion if given in pregnancy",
    evidence_grade: "Strong for ANCA; Moderate for SLE",
    refs: ["ACR/EULAR AAV 2022", "ACR/EULAR SLE 2019"],
  },
  {
    id: "adalimumab",
    name: "Adalimumab (TNFi)",
    class: "TNF-alpha inhibitor (biologic)",
    mechanism: "Human monoclonal antibody against TNF-alpha — blocks both soluble and membrane-bound TNF",
    indications: ["JIA (all subtypes except sJIA)", "JIA-associated uveitis (first-line TNFi)", "ERA/SpA", "Psoriatic JIA"],
    pediatric_dose: "PO weight-based: <15 kg: 10 mg q2w; 15–30 kg: 20 mg q2w; ≥30 kg: 40 mg q2w (SC injection)",
    monitoring: { schedule: "CBC + LFT q3–6 months; ANA, anti-dsDNA baseline", targets: "JADAS target; no infection signals" },
    toxicities: ["Injection site reactions", "Increased infection risk (TB, bacterial, fungal)", "Possible drug-induced lupus (ANA/dsDNA)", "Rare demyelination"],
    contraindications: ["Active serious infection", "Active TB", "CHF NYHA III/IV"],
    tb_screening: "Mandatory TST/IGRA + CXR before starting. Treat latent TB for 1–2 months before biologic.",
    hbv_screening: "HBsAg + anti-HBc — if positive: prophylaxis",
    live_vaccines: "Avoid. Give all live vaccines ≥1 month before biologic. OK for inactivated vaccines.",
    pregnancy: "Compatible through second trimester; avoid third trimester (neonatal immunosuppression)",
    uveitis_note: "Adalimumab SUPERIOR to etanercept for JIA-uveitis — preferred when uveitis present",
    evidence_grade: "Strong (1A) for JIA",
    refs: ["ACR JIA 2022", "ADJUST trial (uveitis)"],
  },
  {
    id: "etanercept",
    name: "Etanercept (TNFi)",
    class: "TNF receptor fusion protein (biologic)",
    mechanism: "Dimeric fusion protein: p75 TNF receptor + IgG1 Fc — binds TNF-alpha and lymphotoxin",
    indications: ["JIA (polyarticular, oligoarticular)", "ERA/SpA (peripheral)", "Psoriatic JIA"],
    pediatric_dose: "0.4 mg/kg (max 25 mg) SC twice weekly OR 0.8 mg/kg (max 50 mg) SC once weekly",
    monitoring: { schedule: "CBC + LFT q3–6 months", targets: "JADAS target" },
    toxicities: ["Injection site reactions", "Increased infection (bacterial)", "Paradoxical psoriasis", "Drug-induced lupus (less than adalimumab)"],
    contraindications: ["Active TB", "Active serious infection", "Septic arthritis of any joint"],
    tb_screening: "Mandatory TST/IGRA before starting",
    live_vaccines: "Avoid live vaccines",
    uveitis_note: "NOT preferred for uveitis — adalimumab superior for ocular inflammation",
    pregnancy: "Compatible (limited data); avoid if possible",
    evidence_grade: "Strong (1A) for JIA polyarticular",
    refs: ["ACR JIA 2022"],
  },
  {
    id: "anakinra",
    name: "Anakinra (IL-1 Receptor Antagonist)",
    class: "IL-1 Inhibitor (biologic)",
    mechanism: "Recombinant IL-1Ra — competitive antagonist at IL-1 receptor type I",
    indications: ["sJIA (first-line biologic)", "MAS/HLH (escalating IV)", "FMF colchicine-resistant", "CAPS (FCAS/MWS)", "PFAPA", "DIRA"],
    pediatric_dose: "1–2 mg/kg/day SC (max 100 mg/day). For MAS: escalate to 4–8 mg/kg IV.",
    monitoring: { schedule: "CBC + LFT monthly initially, then q3 months; injection site check", targets: "Ferritin trend in MAS; no infection" },
    toxicities: ["Injection site reactions (most common — daily SC injection)", "Increased infection risk (bacterial)", "Neutropenia (monitor CBC)"],
    contraindications: ["Active serious infection", "Combination with other biologics (high infection risk)"],
    tb_screening: "TST/IGRA before starting",
    live_vaccines: "Avoid live vaccines",
    advantages: "Flexible dosing (can escalate rapidly IV in MAS); short half-life (can stop quickly if infection)",
    pregnancy: "Limited data — use only if benefit outweighs risk",
    evidence_grade: "Strong for sJIA; Moderate for MAS",
    refs: ["ACR sJIA 2022", "Ravelli MAS 2016"],
  },
  {
    id: "canakinumab",
    name: "Canakinumab (IL-1β Inhibitor)",
    class: "IL-1 Inhibitor (biologic)",
    mechanism: "Human anti-IL-1β monoclonal antibody — highly selective for IL-1β (unlike anakinra which blocks IL-1α too)",
    indications: ["sJIA", "FMF colchicine-resistant", "CAPS (MWS, NOMID)", "TRAPS", "HIDS/MKD"],
    pediatric_dose: "4 mg/kg SC (max 300 mg) every 4 weeks for sJIA; every 8 weeks for FMF/CAPS",
    monitoring: { schedule: "CBC + LFT + SAA level q3 months", targets: "Attack-free; SAA <10 mg/L" },
    toxicities: ["Injection site reactions", "Increased infection risk", "Neutropenia"],
    contraindications: ["Active serious infection", "Active TB"],
    advantages: "Monthly or 8-weekly dosing (better adherence than daily anakinra)",
    tb_screening: "TST/IGRA mandatory",
    live_vaccines: "Avoid live vaccines",
    evidence_grade: "Strong for sJIA and FMF",
    refs: ["PRINTO sJIA trial", "CLUSTER FMF trial"],
  },
  {
    id: "tocilizumab",
    name: "Tocilizumab (IL-6 Inhibitor)",
    class: "IL-6 Receptor Inhibitor (biologic)",
    mechanism: "Humanized anti-IL-6R monoclonal antibody — blocks IL-6 signalling (soluble + membrane IL-6R)",
    indications: ["sJIA (first-line biologic alternative to IL-1i)", "Polyarticular JIA (TNFi failure)", "ERA/SLE refractory"],
    pediatric_dose: {
      sjia: "<30 kg: 12 mg/kg IV q2 weeks; ≥30 kg: 8 mg/kg IV q2 weeks (max 800 mg)",
      poly_jia: "<30 kg: 10 mg/kg IV q4 weeks; ≥30 kg: 8 mg/kg IV q4 weeks",
      sc: "162 mg SC q2 weeks (≥30 kg); 162 mg SC q3 weeks (<30 kg)"
    },
    monitoring: { schedule: "CBC + LFT + lipids q4–8 weeks", targets: "No neutropenia; LFT <3× ULN; lipid management" },
    toxicities: ["Neutropenia", "Hepatotoxicity", "Hyperlipidaemia", "GI perforation (rare — caution in IBD/diverticular disease)", "Infusion reactions"],
    contraindications: ["Active serious infection", "ANC <0.5k", "ALT >3× ULN"],
    caution: "Masks fever/CRP — CRP may be falsely normal even during active infection or MAS",
    tb_screening: "TST/IGRA mandatory",
    live_vaccines: "Avoid live vaccines",
    evidence_grade: "Strong (1A) for sJIA",
    refs: ["TENDER trial", "ACR sJIA 2022"],
  },
  {
    id: "abatacept",
    name: "Abatacept (CTLA4-Ig)",
    class: "T-cell costimulation blocker (biologic)",
    mechanism: "Fusion protein of CTLA-4 + IgG1 Fc — blocks CD28/B7 costimulation, preventing T-cell activation",
    indications: ["JIA polyarticular (TNFi failure)", "JIA-uveitis (TNFi failure)", "SLE refractory"],
    pediatric_dose: "<75 kg: 10 mg/kg IV q4 weeks (after loading doses d1, 15, 29); ≥75 kg: adult dosing 750 mg q4w. SC: 125 mg weekly.",
    monitoring: { schedule: "CBC + LFT q3–6 months", targets: "JADAS target; no infection" },
    toxicities: ["Increased infection risk (lower than TNFi)", "Infusion reactions", "COPD exacerbations (avoid in severe COPD)"],
    contraindications: ["Active serious infection", "Active TB", "Do not combine with TNFi or anakinra"],
    tb_screening: "TST/IGRA mandatory",
    live_vaccines: "Avoid live vaccines",
    advantages: "Better uveitis control than other non-adalimumab options after TNFi failure",
    evidence_grade: "Strong for JIA polyarticular",
    refs: ["PRESTO trial", "ACR JIA 2022"],
  },
  {
    id: "jak_inhibitors",
    name: "JAK Inhibitors (Tofacitinib, Baricitinib, Upadacitinib)",
    class: "Small molecule JAK inhibitor",
    mechanism: "Selective inhibition of JAK1/JAK3 (tofacitinib), JAK1/2 (baricitinib, upadacitinib) — blocks cytokine signalling",
    indications: ["RF+ polyarticular JIA (tofacitinib ≥2y approved)", "ERA refractory", "MAS/HLH (ruxolitinib — JAK1/2)", "Refractory uveitis (tofacitinib)"],
    pediatric_dose: "Tofacitinib: 5 mg PO BID (≥10 kg — weight-based dosing available as solution). Baricitinib: 1–4 mg OD (age/weight dependent).",
    monitoring: { schedule: "CBC + LFT + lipids q4–8 weeks initially", targets: "No lymphopenia; no hepatotoxicity" },
    toxicities: ["Herpes zoster (increased risk)", "Infections (serious bacterial, fungal, opportunistic)", "VTE risk (baricitinib — JAK2)", "Dyslipidaemia", "Malignancy (long-term surveillance)"],
    contraindications: ["Active serious infection", "Active TB", "ANC <0.5k"],
    tb_screening: "TST/IGRA mandatory before starting",
    live_vaccines: "Avoid all live vaccines. Varicella vaccination BEFORE starting (high HZ risk)",
    special_note: "Ruxolitinib (JAK1/2): used for refractory MAS/HLH — 10–20 mg BID (adult dosing)",
    evidence_grade: "Strong for RF+ JIA (tofacitinib); Moderate for ERA",
    refs: ["YAZOLE trial (tofacitinib)", "SELECT-JIA trial (upadacitinib)"],
  },
];

export const DRUG_CLASSES = ["All", "DMARD", "Biologic", "IL-1 Inhibitor", "TNFi", "Immunosuppressant", "Antimalarial", "JAK inhibitor"];