// ── Vasculitis Expansion Layer ────────────────────────────────────────────
// New vasculitis disease cards: Takayasu, PAN, Behcet, CNS Vasculitis, MIS-C overlap

export const VASCULITIS_CONDITIONS = [
  {
    id: "takayasu",
    name: "Takayasu Arteritis",
    category: "Vasculitis",
    urgency: "critical",
    icd: "M31.4",
    guideline: "ACR/EULAR TAK 2022 + SHARE 2019 + PRINTO",
    tags: ["Large Vessel", "Aorta", "Stenosis", "Biologic", "MRI Angio"],
    variants: ["Type I (aortic arch + branches)", "Type IIa (ascending aorta)", "Type IIb (descending thoracic)", "Type III (combined)", "Type IV (abdominal)", "Type V (diffuse)"],
    overview: "Large vessel vasculitis involving aorta and main branches. Peak onset adolescent females. Presents with limb claudication, BP discrepancy, carotidodynia, constitutional symptoms. MRI/MRA gold standard for active disease.",
    classification: "ACR 2022: age <40 at diagnosis + ≥2 of: decreased brachial pulse, BP difference >10mmHg, bruit (aorta/subclavian), claudication, imaging evidence",
    diagnostic_criteria: [
      "Age <40 at disease onset",
      "Claudication of extremities",
      "Decreased or absent brachial artery pulse",
      "BP difference >10 mmHg between arms",
      "Bruit over subclavian arteries or aorta",
      "Arteriographic narrowing/occlusion of aorta or major branches",
    ],
    flowchart: [
      "Suspect: young female + hypertension + BP asymmetry + constitutional symptoms",
      "Labs: ESR, CRP, CBC, ANA, ANCA (exclude mimics); inflammatory markers active disease",
      "Imaging: MRI/MRA aorta + branches — luminal + wall changes (gold standard)",
      "CT angiography if MRI contraindicated; PET-CT for active inflammatory phase",
      "Assess for renal artery stenosis — common cause of HTN in TAK",
      "Prednisolone 1 mg/kg/day (max 60 mg) — induction",
      "Add steroid-sparing: MTX 15 mg/m²/week OR MMF 600 mg/m² BID early",
      "Biologic if inadequate response: tocilizumab (preferred) OR TNFi",
      "Revascularization: only in stable/remission phase — percutaneous or surgical",
    ],
    decision_nodes: [
      { q: "Active disease (rising ESR/CRP + new imaging changes)?", yes: "Prednisolone + tocilizumab (IL-6i) — superior to TNFi for TAK", no: "Maintain steroid-sparing DMARD (MTX/MMF), taper steroids" },
      { q: "Renal artery stenosis causing refractory HTN?", yes: "Nephrology + interventional radiology: renal artery angioplasty in remission", no: "Antihypertensives (ACEi/ARB) — first-line for TAK-HTN" },
    ],
    key_points: [
      "BP in both arms + all 4 limbs mandatory — asymmetry is diagnostic",
      "Tocilizumab (IL-6i): superior to TNFi, now preferred biologic",
      "MTX or MMF as steroid-sparing DMARD — early initiation",
      "Revascularization ONLY in remission phase — active disease increases restenosis risk",
      "Renal artery stenosis: ACEi first-line; ACEi/ARB contraindicated with bilateral RAS",
      "ITAS-A/PVAS: disease activity scoring for monitoring",
      "Annual surveillance MRI angiography for vascular progression",
    ],
    monitoring: ["ESR, CRP monthly during active disease", "ITAS-A/PVAS score", "MRI/MRA q6–12 months", "BP both arms every visit", "Renal function + urine PCR"],
    drugs: ["Prednisolone", "Methotrexate", "MMF", "Tocilizumab (preferred biologic)", "Adalimumab", "Infliximab", "Aspirin (low-dose)"],
    emergency_flags: ["Aortic dissection", "Stroke/TIA (carotid stenosis)", "Hypertensive emergency (renal artery stenosis)", "Ischaemic limb"],
    renal_overlap: ["Renal artery stenosis → renovascular HTN → CKD", "ACEi/ARB first-line for TAK hypertension", "Monitor GFR — revascularisation planning with nephrology"],
    gnLink: "htn-treatment",
    prognosis: "Chronic relapsing course in 50%. Morbidity from vascular complications (HTN, stroke, ischaemia). Mortality low with modern biologics.",
    refs: [
      { title: "ACR/EULAR TAK Guidelines 2022", url: "https://www.rheumatology.org/" },
      { title: "SHARE TAK Recommendations 2019", url: "https://www.eular.org/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-06",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "pan",
    name: "Polyarteritis Nodosa (PAN)",
    category: "Vasculitis",
    urgency: "critical",
    icd: "M30.0",
    guideline: "EULAR PAN Recommendations 2009 + SHARE 2019 + ACR/EULAR 2022",
    tags: ["Medium Vessel", "Renal Aneurysm", "Mononeuritis", "HBV-PAN", "Cutaneous PAN"],
    variants: ["Systemic PAN", "Cutaneous PAN (benign)", "HBV-associated PAN", "Deficiency of ADA2 (DADA2)"],
    overview: "Medium vessel necrotizing vasculitis without ANCA. Affects medium and small muscular arteries. Classically: weight loss, fever, mononeuritis multiplex, renal/mesenteric aneurysms. Rare in children — exclude DADA2.",
    classification: "ACR 1990 (adults): ≥3 of 10 criteria. Pediatric: EULAR/PRINTO/PReS classification for childhood PAN",
    diagnostic_criteria: [
      "Weight loss ≥4 kg",
      "Livedo reticularis",
      "Testicular pain/tenderness",
      "Myalgia/leg weakness",
      "Mononeuropathy or polyneuropathy",
      "Diastolic BP >90 mmHg",
      "Elevated creatinine",
      "HBsAg or HBV-DNA positive",
      "Arteriographic abnormality (aneurysm/occlusion)",
      "Biopsy: PMN in arterial wall",
    ],
    flowchart: [
      "Suspect PAN: fever + weight loss + mononeuritis multiplex + mesenteric/renal symptoms",
      "Labs: ANCA (negative — rule out AAV), HBsAg/HBV-DNA, CBC, ESR, CRP, creatinine",
      "In children: DADA2 testing (ADA2 enzyme/gene — autosomal recessive form)",
      "Angiography (CT or MR): renal/mesenteric aneurysms + stenoses",
      "Biopsy: sural nerve or skin nodule — necrotizing arteritis without granuloma",
      "HBV-PAN: antiviral (entecavir) + plasma exchange → short steroid course",
      "Non-HBV: prednisolone 1 mg/kg/day + CYC (severe) or MTX (mild-moderate)",
      "DADA2: TNFi (adalimumab/etanercept) — dramatic response",
    ],
    decision_nodes: [
      { q: "ADA2 enzyme low or CECR1 mutation (DADA2)?", yes: "TNFi (adalimumab/etanercept) — first-line specific therapy; avoid steroids as sole treatment", no: "Standard PAN: prednisolone + CYC (severe) or MTX (moderate)" },
      { q: "HBsAg positive (HBV-associated PAN)?", yes: "Antiviral therapy (entecavir) + plasma exchange → taper steroids early", no: "Idiopathic PAN: standard immunosuppression protocol" },
    ],
    key_points: [
      "ANCA NEGATIVE — key differentiator from ANCA vasculitis",
      "In children: always test for DADA2 (ADA2 enzyme + CECR1 gene)",
      "DADA2: TNFi is curative — dramatically different from standard PAN management",
      "Renal aneurysms (not nephritis) — different from ANCA vasculitis",
      "HBV-PAN: antiviral + PE + short steroids — avoid prolonged immunosuppression",
      "Mesenteric vasculitis: abdominal pain, infarction risk — urgent imaging",
      "No nephritis (proteinuria/haematuria) — if present, consider ANCA or other GN",
    ],
    monitoring: ["BVAS score", "ESR, CRP monthly", "Creatinine, urine dipstick", "BP monitoring", "Nerve conduction study (neuropathy)"],
    drugs: ["Prednisolone", "Cyclophosphamide (severe)", "Methotrexate (moderate)", "Adalimumab/Etanercept (DADA2)", "Entecavir (HBV-PAN)", "Aspirin"],
    emergency_flags: ["Mesenteric ischaemia/infarction", "Renovascular hypertensive crisis", "Ruptured renal aneurysm", "Stroke (cerebral vasculitis overlap)"],
    renal_overlap: ["Renovascular HTN from renal artery aneurysms", "Monitor GFR — not nephritis but ischaemic nephropathy possible", "ACEi with caution if bilateral renal aneurysms"],
    gnLink: "htn-emergency",
    prognosis: "Cutaneous PAN: benign, self-limiting. Systemic PAN: 50% 5y remission with treatment. DADA2 — excellent TNFi response.",
    refs: [
      { title: "SHARE PAN Recommendations 2019", url: "https://www.eular.org/" },
      { title: "DADA2 Review — Navon Elkan 2014", url: "https://pubmed.ncbi.nlm.nih.gov/24482247/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-05",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "behcet",
    name: "Behçet Disease",
    category: "Vasculitis",
    urgency: "high",
    icd: "M35.2",
    guideline: "EULAR Behçet 2018 + ICBD Criteria 2014",
    tags: ["Oral Ulcers", "Uveitis", "DVT", "Genital Ulcers", "Colchicine"],
    variants: ["Mucocutaneous-dominant", "Ocular Behçet", "Vascular Behçet (arterial/venous)", "Neuro-Behçet", "Intestinal Behçet"],
    overview: "Variable vessel vasculitis with recurrent oral ulcers, genital ulcers, uveitis, skin lesions. Rare in young children. HLA-B51 positive in ~60%. DVT/pulmonary artery aneurysm in vascular Behçet.",
    classification: "ICBD 2014: oral ulcers (2 pts), genital ulcers (2), ocular (2), skin (1), neurological (1), vascular (1), pathergy (1). ≥4 points = Behçet.",
    diagnostic_criteria: [
      "Recurrent oral ulcers (≥3/year) — most common",
      "Genital ulcers",
      "Eye lesions: anterior/posterior uveitis or retinal vasculitis",
      "Skin: pseudofolliculitis, erythema nodosum, acneiform lesions",
      "Vascular involvement: DVT, arterial aneurysm",
      "Neurological (parenchymal or vascular)",
    ],
    flowchart: [
      "Recurrent painful oral ulcers: consider Behçet if ≥3/year + other features",
      "Complete pathergy test (skin prick — positive in 20–60%)",
      "Ophthalmology: slit-lamp + fundus — posterior uveitis/retinal vasculitis",
      "Imaging: vascular (CTA/MRA), CNS MRI if neurological symptoms",
      "Mucocutaneous: colchicine 0.5–1 mg/day (oral/genital ulcers) ± topical steroids",
      "Ocular: azathioprine/cyclosporin + prednisolone ± infliximab (severe)",
      "Vascular Behçet: immunosuppression + anticoagulation (venous thrombosis)",
      "Neuro-Behçet: IV methylprednisolone + MTX/AZA; infliximab for refractory",
    ],
    decision_nodes: [
      { q: "Posterior uveitis or retinal vasculitis?", yes: "Azathioprine + prednisolone ± cyclosporin. Infliximab if vision-threatening.", no: "Anterior uveitis: topical steroids + cycloplegics. Colchicine for mucocutaneous." },
      { q: "Pulmonary artery aneurysm or venous thrombosis?", yes: "IV methylprednisolone + CYC + anticoagulation (DVT). TNFi for refractory.", no: "Colchicine/AZA for mucocutaneous/arthritis" },
    ],
    key_points: [
      "Colchicine: first-line for mucocutaneous and articular Behçet",
      "Azathioprine: prevents new eye attacks — start early in ocular disease",
      "Infliximab: ocular refractory or neuro-Behçet",
      "Vascular Behçet (aneurysm): surgery risk — prefer medical immunosuppression",
      "HLA-B51 positive: higher risk of severe ocular and vascular involvement",
      "No live vaccines if on azathioprine or biologics",
    ],
    monitoring: ["Ophthalmology q3–6 months", "ESR, CRP", "CBC on AZA", "MRI brain (neuro-Behçet)", "Vascular imaging annually"],
    drugs: ["Colchicine", "Topical steroids", "Azathioprine", "Prednisolone", "Cyclosporin", "Infliximab", "Thalidomide (oral ulcers, restricted use)"],
    emergency_flags: ["Ruptured pulmonary artery aneurysm (haemoptysis)", "Catastrophic CNS thrombosis", "Bilateral posterior uveitis (vision loss)", "Intestinal perforation"],
    renal_overlap: ["Renal amyloidosis (rare long-term)", "Renal vein thrombosis (vascular Behçet)", "Monitor urine annually for amyloid"],
    gnLink: null,
    prognosis: "Variable by organ involvement. Ocular — vision loss risk. Vascular and neurological — worst prognosis.",
    refs: [
      { title: "EULAR Behçet Recommendations 2018", url: "https://www.eular.org/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-04",
    review_status: "EXPERT_REVIEWED",
  },
  {
    id: "cns_vasculitis",
    name: "CNS Vasculitis (cPACNS)",
    category: "Vasculitis",
    urgency: "critical",
    icd: "I68.2",
    guideline: "Canadian cPACNS Consensus + European Vasculitis Study Group",
    tags: ["Stroke", "Seizure", "MRI Angio", "Small Vessel", "Large Vessel", "Biopsy"],
    variants: ["Angiography-positive (large/medium vessel)", "Angiography-negative/small vessel (biopsy needed)", "Progressive vs non-progressive"],
    overview: "Primary CNS vasculitis in children (cPACNS). Presents with stroke, seizures, encephalopathy, neuropsychiatric symptoms. Angiography-positive (large vessel) vs angiography-negative (small vessel). Rare but devastating.",
    diagnostic_criteria: [
      "Neurological deficits not explained by other cause",
      "MRI brain: ischaemic/inflammatory changes",
      "Cerebral angiography (MRA/CTA/DSA): vessel wall irregularity",
      "CSF: pleocytosis in small vessel cPACNS",
      "Brain biopsy: gold standard for small vessel (angiography-negative)",
    ],
    flowchart: [
      "Acute neurological deficit: stroke in young child — rule out cardiac, thrombophilia, metabolic",
      "MRI brain + MRA (gadolinium) + DSA if angio-positive suspected",
      "CSF analysis: pleocytosis, protein (small vessel cPACNS)",
      "Vessel wall imaging (high-resolution MRI) — enhancing vessel wall = active inflammation",
      "Angiography-positive: aspirin + prednisolone 2 mg/kg/day (non-progressive) OR CYC (progressive)",
      "Angiography-negative (small vessel): brain biopsy for histology + aggressive immunosuppression",
      "Induction: IV methylprednisolone + CYC (or rituximab) for progressive disease",
      "Maintenance: AZA or MMF for 18–24 months",
    ],
    decision_nodes: [
      { q: "Progressive neurological deterioration despite steroids?", yes: "Pulse CYC induction (or rituximab) + IV methylprednisolone pulses", no: "Aspirin + prednisolone for non-progressive angiography-positive cPACNS" },
      { q: "Angiography negative (normal vessels on MRA/DSA)?", yes: "Small vessel cPACNS likely — brain biopsy for confirmation; treat aggressively", no: "Angiography-positive: stratify by progressive vs non-progressive" },
    ],
    key_points: [
      "Brain MRI with vessel wall imaging is key — routine MRI may be normal",
      "DSA > MRA for sensitivity in large vessel cPACNS",
      "Non-progressive angiography-positive: aspirin + steroids, good prognosis",
      "Progressive: IV CYC (or rituximab) induction + long maintenance",
      "Small vessel: brain biopsy mandatory — cannot be treated empirically without histology",
      "Aspirin: anti-platelet throughout treatment",
      "Risk of stroke recurrence without treatment: 30–40%",
    ],
    monitoring: ["MRI brain q3–6 months", "Vessel wall MRI (activity)", "Neuropsychological assessment", "CBC, LFT on immunosuppression", "DSA if clinical deterioration"],
    drugs: ["Aspirin", "Prednisolone", "IV Methylprednisolone", "Cyclophosphamide", "Rituximab", "Azathioprine (maintenance)", "MMF (maintenance)"],
    emergency_flags: ["Acute stroke/TIA", "Status epilepticus", "Acute encephalopathy", "Haemorrhagic transformation of infarct"],
    renal_overlap: ["Secondary hypertension from steroids/CYC", "CYC gonadotoxicity counselling", "Monitor creatinine during CYC"],
    gnLink: null,
    prognosis: "Non-progressive: 80% remission. Progressive/small vessel: 50% residual deficits. Early aggressive treatment critical.",
    refs: [
      { title: "Canadian cPACNS Consensus 2020", url: "https://pubmed.ncbi.nlm.nih.gov/" },
    ],
    evidence_grade: "Moderate",
    last_updated: "2024-03",
    review_status: "EXPERT_REVIEWED",
  },
];

export const VASCULITIS_CATEGORY = "Vasculitis";