import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Copy, Printer, Check } from "lucide-react";
import { toast } from "sonner";

export default function ReportActions({ title = "Analysis Report", result, summary = "", printId }) {
  const [copied, setCopied] = useState(false);

  function handlePrint() {
    if (printId) {
      const el = document.getElementById(printId);
      if (!el) return;
      const html = `<!DOCTYPE html><html><head><title>${title}</title>
        <style>
          body { font-family: Arial, sans-serif; font-size: 12px; padding: 20px; color: #1a1a1a; }
          h1 { font-size: 16px; margin-bottom: 4px; }
          .meta { color: #666; font-size: 10px; margin-bottom: 16px; }
          * { box-sizing: border-box; }
          @media print { body { padding: 0; } }
        </style>
      </head><body>
        <h1>${title}</h1>
        <p class="meta">Generated by CIEE Clinicals · ${new Date().toLocaleString()}</p>
        ${el.innerHTML}
      </body></html>`;
      const win = window.open("", "_blank");
      win.document.write(html);
      win.document.close();
      win.focus();
      win.print();
      win.close();
    } else {
      window.print();
    }
  }

  function handleCopy() {
    const lines = [
      `=== ${title} ===`,
      `Generated: ${new Date().toLocaleString()}`,
      `Powered by CIEE Clinicals`,
      "",
      summary || buildTextSummary(result),
      "",
      "--- Disclaimer ---",
      "This is a clinical decision-support tool. Clinical correlation required.",
    ];
    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true);
      toast.success("Report copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => toast.error("Could not copy — please try manually"));
  }

  function handleDownload() {
    if (!result) return;
    const payload = {
      title,
      generated_at: new Date().toISOString(),
      source: "CIEE Clinicals",
      data: result,
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "_")}_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded");
  }

  return (
    <div className="flex items-center gap-2 flex-wrap pt-2 border-t border-slate-200 mt-2">
      <span className="text-xs text-slate-400 mr-auto">Save or share this report</span>
      <Button variant="outline" size="sm" className="gap-1.5 text-xs h-8" onClick={handleCopy}>
        {copied ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
        {copied ? "Copied" : "Copy"}
      </Button>
      <Button variant="outline" size="sm" className="gap-1.5 text-xs h-8" onClick={handlePrint}>
        <Printer className="w-3.5 h-3.5" />
        Save PDF
      </Button>
      {result && (
        <Button variant="outline" size="sm" className="gap-1.5 text-xs h-8" onClick={handleDownload}>
          <Download className="w-3.5 h-3.5" />
          JSON
        </Button>
      )}
    </div>
  );
}

function buildTextSummary(result) {
  if (!result) return "";
  const lines = [];
  if (result.acmg_class) {
    lines.push(`ACMG Classification: ${result.acmg_class}`);
    if (result.gene_identified) lines.push(`Gene: ${result.gene_identified}`);
    if (result.variant_hgvs) lines.push(`Variant: ${result.variant_hgvs}`);
    if (result.zygosity) lines.push(`Zygosity: ${result.zygosity}`);
    if (result.acmg_classification_rationale) lines.push(`Rationale: ${result.acmg_classification_rationale}`);
    if (result.prescription_suppressor_triggered) lines.push("⚠ CNI CONTRAINDICATED — Prescription Suppressor Activated");
    if (result.management_implications?.length) lines.push("Management: " + result.management_implications.join("; "));
  }
  if (result.primary_interpretation) {
    lines.push(`Interpretation: ${result.primary_interpretation}`);
    if (result.ckd_stage) lines.push(`CKD Stage: ${result.ckd_stage}`);
    if (result.aki_stage) lines.push(`AKI Stage: ${result.aki_stage}`);
    const ev = result.extracted_values;
    if (ev?.creatinine_mg_dL) lines.push(`Creatinine: ${ev.creatinine_mg_dL} mg/dL`);
    if (ev?.egfr_used) lines.push(`eGFR: ${ev.egfr_used.toFixed(1)} mL/min/1.73m²`);
    if (result.critical_values?.length) lines.push("Critical: " + result.critical_values.join("; "));
    if (result.treatment_recommendations?.length) lines.push("Treatment: " + result.treatment_recommendations.join("; "));
  }
  if (result.primary_diagnosis && !result.primary_interpretation) {
    lines.push(`Diagnosis: ${result.primary_diagnosis}`);
    if (result.histology_class) lines.push(`Histology: ${result.histology_class}`);
    if (result.severity_grade) lines.push(`Severity: ${result.severity_grade}`);
    if (result.prognosis) lines.push(`Prognosis: ${result.prognosis}`);
    if (result.treatment_recommendations?.length) lines.push("Treatment: " + result.treatment_recommendations.join("; "));
  }
  if (result.evidence_grade) lines.push(`Evidence Grade: ${result.evidence_grade}`);
  if (result.guideline_ref) lines.push(`Guideline: ${result.guideline_ref}`);
  return lines.join("\n");
}
