import React, { useState } from "react";
import { base44 } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Download, Loader2, BookOpen, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { EMERGENCY_PROTOCOLS } from "@/lib/guidelines/index";

const EXPORT_TYPES = [
  { value: "handbook", label: "📚 Pocket Handbook", desc: "Full structured reference" },
  { value: "emergency", label: "⚡ Emergency Guide", desc: "Quick protocols only" },
  { value: "teaching", label: "🎓 Teaching Booklet", desc: "For resident/fellow education" },
  { value: "prescriber", label: "💊 Prescriber Reference", desc: "Drug dosing & protocols" },
];

export default function HandbookExporter({ allGuidelines }) {
  const [exportType, setExportType] = useState("handbook");
  const [selectedIds, setSelectedIds] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [exportedUrl, setExportedUrl] = useState(null);

  const toggleId = (id) =>
    setSelectedIds(prev => prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]);

  const selectAll = () => setSelectedIds(allGuidelines.map(g => g.id));
  const clearAll = () => setSelectedIds([]);

  const selectedGuidelines = allGuidelines.filter(g => selectedIds.includes(g.id));

  const generateHandbook = async () => {
    if (selectedGuidelines.length === 0 && exportType !== "emergency") {
      toast.error("Select at least one guideline");
      return;
    }
    setGenerating(true);
    setExportedUrl(null);
    toast.loading("Generating handbook…", { id: "hb" });
    try {
      let content = "";

      if (exportType === "emergency") {
        content = `# PEDIATRIC NEPHROLOGY EMERGENCY QUICK REFERENCE\n\nGenerated by CliniCals · ${new Date().toLocaleDateString()}\n\n---\n\n`;
        EMERGENCY_PROTOCOLS.forEach((p, i) => {
          content += `## ${i + 1}. ${p.icon} ${p.title}\n\n`;
          p.steps.forEach((s, j) => { content += `${j + 1}. ${s}\n`; });
          content += "\n---\n\n";
        });
      } else {
        const typeLabel = EXPORT_TYPES.find(t => t.value === exportType)?.label || "Handbook";
        content = `# PEDIATRIC NEPHROLOGY ${typeLabel.toUpperCase()}\n\nCliniCals by Swarnim · ${new Date().toLocaleDateString()}\n\n---\n\n`;

        if (exportType === "emergency") {
          content += "## EMERGENCY PROTOCOLS\n\n";
          EMERGENCY_PROTOCOLS.forEach(p => {
            content += `### ${p.icon} ${p.title}\n`;
            p.steps.forEach((s, j) => { content += `${j + 1}. ${s}\n`; });
            content += "\n";
          });
        }

        selectedGuidelines.forEach((g, gi) => {
          content += `## ${gi + 1}. ${g.title}\n`;
          content += `**Source:** ${g.source} ${g.year} · **Category:** ${g.category}\n\n`;
          if (g.scope_and_population || g.summary) {
            content += `### Clinical Summary\n${g.scope_and_population || g.summary}\n\n`;
          }
          if (g.key_recommendations?.length > 0) {
            content += `### Management Algorithm\n`;
            g.key_recommendations.forEach((r, ri) => { content += `${ri + 1}. ${r}\n`; });
            content += "\n";
          }
          if (g.practice_pearls?.length > 0) {
            content += `### Clinical Pearls\n`;
            g.practice_pearls.forEach(p => { content += `• ${p}\n`; });
            content += "\n";
          }
          content += "---\n\n";
        });

        content += "\n\n*Educational reference only. Apply clinical judgment. Not a substitute for senior clinical supervision.*\n";
      }

      // Use AI to enhance the content if teaching mode
      let finalContent = content;
      if (exportType === "teaching" && selectedGuidelines.length > 0) {
        const enhanced = await base44.integrations.Core.InvokeLLM({
          prompt: `You are creating a teaching booklet for pediatric nephrology residents. Format this guideline content as a structured teaching document with: learning objectives, key facts to remember, viva questions at the end of each guideline, and an index. Keep clinical accuracy.\n\nContent:\n${content.slice(0, 4000)}`,
          response_json_schema: {
            type: "object",
            properties: { formatted_content: { type: "string" } }
          }
        });
        finalContent = enhanced.formatted_content || content;
      }

      // Create downloadable text file
      const blob = new Blob([finalContent], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      setExportedUrl(url);
      toast.success("Handbook ready for download!", { id: "hb" });
    } catch { toast.error("Export failed", { id: "hb" }); }
    finally { setGenerating(false); }
  };

  const categories = [...new Set(allGuidelines.map(g => g.category).filter(Boolean))];

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 mb-2">
        <FileText className="w-5 h-5 text-emerald-600" />
        <div>
          <p className="text-sm font-bold text-slate-900">Downloadable Handbook Mode</p>
          <p className="text-xs text-slate-500">Export PDF · Teaching Booklet · Emergency Guide · Pocket Manual</p>
        </div>
      </div>

      {/* Export type */}
      <div className="grid grid-cols-2 gap-1.5">
        {EXPORT_TYPES.map(t => (
          <button key={t.value} onClick={() => setExportType(t.value)}
            className={`p-2.5 rounded-xl border-2 text-left transition-all ${exportType === t.value ? "border-emerald-400 bg-emerald-50" : "border-slate-200 bg-white hover:border-emerald-200"}`}>
            <p className={`text-xs font-bold ${exportType === t.value ? "text-emerald-700" : "text-slate-700"}`}>{t.label}</p>
            <p className="text-xs text-slate-400 mt-0.5">{t.desc}</p>
          </button>
        ))}
      </div>

      {/* Guideline selector (not needed for emergency-only) */}
      {exportType !== "emergency" && (
        <div>
          <div className="flex items-center justify-between mb-2">
            <p className="text-xs font-bold text-slate-600">Select Guidelines</p>
            <div className="flex gap-2">
              <button onClick={selectAll} className="text-xs text-blue-600 hover:underline">All</button>
              <button onClick={clearAll} className="text-xs text-slate-400 hover:underline">Clear</button>
            </div>
          </div>
          <div className="max-h-48 overflow-y-auto space-y-1 border border-slate-200 rounded-xl p-2 bg-slate-50">
            {allGuidelines.map(g => (
              <label key={g.id} className="flex items-center gap-2 p-1.5 rounded-lg hover:bg-white cursor-pointer">
                <Checkbox checked={selectedIds.includes(g.id)} onCheckedChange={() => toggleId(g.id)} />
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium text-slate-800 truncate">{g.title}</p>
                  <p className="text-xs text-slate-400">{g.source} · {g.year}</p>
                </div>
                {selectedIds.includes(g.id) && <Badge className="text-xs bg-emerald-100 text-emerald-700 border-0">✓</Badge>}
              </label>
            ))}
          </div>
          {selectedIds.length > 0 && (
            <p className="text-xs text-slate-500 mt-1">{selectedIds.length} selected</p>
          )}
        </div>
      )}

      <Button onClick={generateHandbook} disabled={generating}
        className="w-full h-9 text-sm bg-emerald-600 hover:bg-emerald-700">
        {generating
          ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Generating…</>
          : <><Sparkles className="w-4 h-4 mr-2" />Generate {EXPORT_TYPES.find(t => t.value === exportType)?.label}</>}
      </Button>

      {exportedUrl && (
        <a href={exportedUrl} download={`nephrology_${exportType}_${new Date().toISOString().split("T")[0]}.txt`}>
          <Button className="w-full h-9 text-sm bg-blue-600 hover:bg-blue-700">
            <Download className="w-4 h-4 mr-2" />Download Handbook
          </Button>
        </a>
      )}
    </div>
  );
}